#! /usr/bin/env python3
# -*- coding: utf-8 -*-

'''Data on the show Steven Universe.'''

title = 'Steven Universe'

# Dict of episode numbers and titles. Double-length episodes are instead indexed with a string
# containing the episode numbers they take up, separated by a forward slash (/), or with a
# dash for > 2-part episodes. This number or string will appear in the node hovertext.
# Dicts are now conveniently ordered as of python 3.7 papa bless
episodes = {
    1: 'Gem Glow',
    2: 'Laser Light Cannon',
    3: 'Cheeseburger Backpack',
    4: 'Together Breakfast',
    5: 'Frybo',
    6: 'Cat Fingers',
    7: 'Bubble Buddies',
    8: 'Serious Steven',
    9: 'Tiger Millionaire',
    10: "Steven's Lion",
    11: 'Arcade Mania',
    12: 'Giant Woman',
    13: 'So Many Birthdays',
    14: 'Lars and the Cool Kids',
    15: 'Onion Trade',
    16: 'Steven the Sword Fighter',
    17: 'Lion 2: The Movie',
    18: 'Beach Party',
    19: "Rose's Room",
    20: 'Coach Steven',
    21: 'Joking Victim',
    22: 'Steven and the Stevens',
    23: 'Monster Buddies',
    24: 'An Indirect Kiss',
    25: 'Mirror Gem',
    26: 'Ocean Gem',
    27: 'House Guest',
    28: 'Space Race',
    29: 'Secret Team',
    30: 'Island Adventure',
    31: 'Keep Beach City Weird',
    32: 'Fusion Cuisine',
    33: "Garnet's Universe",
    34: 'Watermelon Steven',
    35: 'Lion 3: Straight to Video',
    36: 'Warp Tour',
    37: 'Alone Together',
    38: 'The Test',
    39: 'Future Vision',
    40: 'On the Run',
    41: 'Horror Club',
    42: 'Winter Forecast',
    43: 'Maximum Capacity',
    44: 'Marble Madness',
    45: "Rose's Scabbard",
    46: 'Open Book',
    47: 'Shirt Club',
    48: 'Story for Steven',
    49: 'The Message',
    50: 'Political Power',
    51: 'The Return',
    52: 'Jail Break',
    53: 'Full Disclosure',
    54: 'Joy Ride',
    55: 'Say Uncle',
    56: 'Love Letters',
    57: 'Reformed',
    58: 'Sworn to the Sword',
    59: 'Rising Tides, Crashing Skies',
    60: 'Keeping It Together',
    61: 'We Need to Talk',
    62: 'Chille Tid',
    63: 'Cry for Help',
    64: 'Keystone Motel',
    65: 'Onion Friend',
    66: 'Historical Friction',
    67: 'Friend Ship',
    68: 'Nightmare Hospital',
    69: "Sadie's Song",
    70: 'Catch and Release',
    71: 'When It Rains',
    72: 'Back to the Barn',
    73: 'Too Far',
    74: 'The Answer',
    75: "Steven's Birthday",
    76: "It Could've Been Great",
    77: 'Message Received',
    78: 'Log Date 7 15 2',
    79: 'Super Watermelon Island',
    80: 'Gem Drill',
    81: 'Same Old World',
    82: 'Barn Mates',
    83: 'Hit the Diamond',
    84: 'Steven Floats',
    85: 'Drop Beat Dad',
    86: 'Mr. Greg',
    87: 'Too Short to Ride',
    88: 'The New Lars',
    89: 'Beach City Drift',
    90: 'Restaurant Wars',
    91: "Kiki's Pizza Delivery Service",
    92: 'Monster Reunion',
    93: 'Alone at Sea',
    94: 'Greg the Babysitter',
    95: 'Gem Hunt',
    96: 'Crack the Whip',
    97: 'Steven vs. Amethyst',
    '98/99': 'Bismuth',
    100: 'Beta',
    101: 'Earthlings',
    102: 'Back to the Moon',
    103: 'Bubbled',
    104: 'Kindergarten Kid',
    105: 'Know Your Fusion',
    106: "Buddy's Book",
    107: 'Mindful Education',
    108: 'Future Boy Zoltron',
    109: 'Last One Out of Beach City',
    110: 'Onion Gang',
    '111/112': 'Gem Harvest',
    113: 'Three Gems and a Baby',
    114: "Steven's Dream",
    115: 'Adventures in Light Distortion',
    116: 'Gem Heist',
    117: 'The Zoo',
    118: 'That Will Be All',
    119: 'The New Crystal Gems',
    120: 'Storm in the Room',
    121: 'Rocknaldo',
    122: 'Tiger Philanthropist',
    123: 'Room for Ruby',
    124: 'Lion 4: Alternate Ending',
    125: 'Doug Out',
    126: 'The Good Lars',
    127: 'Are You My Dad?',
    128: 'I Am My Mom',
    129: 'Stuck Together',
    130: 'The Trial',
    131: 'Off Colors',
    132: "Lars' Head",
    133: 'Dewey Wins',
    134: 'Gemcation',
    135: 'Raising the Barn',
    136: 'Back to the Kindergarten',
    137: 'Sadie Killer',
    138: 'Kevin Party',
    139: 'Lars of the Stars',
    140: 'Jungle Moon',
    141: 'Your Mother and Mine',
    142: 'The Big Show',
    143: 'Pool Hopping',
    144: 'Letters to Lars',
    145: "Can't Go Back",
    146: 'A Single Pale Rose',
    147: "Now We're Only Falling Apart",
    148: "What's Your Problem",
    149: 'The Question',
    150: 'Made of Honor',
    '151/152': 'Reunited',
    153: 'Legs From Here to Homeworld',
    154: 'Familiar',
    155: 'Together Alone',
    156: 'Escapism',
    '157-160': 'Change Your Mind'
}

# Season colors also set to match Wikipedia
# (Section colors from https://en.wikipedia.org/wiki/List_of_Steven_Universe_episodes)
seasons = {1: dict(start=1, end=52, color='#FF5E6D'),
           2: dict(start=53, end=78, color='#91ECDD'),
           3: dict(start=79, end=103, color='#B895D1'),
           4: dict(start=104, end=128, color='#A12766'),
           5: dict(start=129, end=160, color='#ACDF7D')}

# Episodes that logically 'follow' each other directly in the plot
plot_threads = [
    (1, 23, r'''Centipeedle arc'''),
    (23, 92, r'''Centipeedle arc'''),
    (92, 153, r'''Centipeedle arc'''),
    (3, 38, r'''Sea Spire test'''),
    (9, 122, r'''Wrestling arc'''),
    (10, 17, r'''Lion arc'''),
    (17, 35, r'''Lion arc'''),
    (35, 45, r'''Lion arc'''),
    (17, 45, r'''Rose's Sword/Armory'''),
    (24, 26, r'''Steven's healing power'''),
    (26, 27, r'''Steven's healing power'''),
    (27, 92, r'''Steven's healing power'''),
    (25, 26, r'''Lapis arc'''),
    (26, 49, r'''Lapis arc'''),
    (26, 27, r'''Greg's broken leg'''),
    (28, 36, r'''Galaxy warp checking'''),
    (34, 79, r'''Watermelon Stevens'''),
    (35, 98, r'''Bismuth's gem'''),
    (35, 124, r'''Rose's tape for Steven'''),
    (35, 132, r'''Mystery of Lion's nature'''),
    (36, 44, r'''Peridot arc'''),
    (37, 89, r'''Kevin arc'''),
    (89, 138, r'''Kevin arc'''),
    (39, 42, r'''Garnet's future vision'''),
    (44, 49, r'''Homeworld gems invasion arc'''),
    (49, 50, r'''Homeworld gems invasion arc'''),
    (50, 51, r'''Homeworld gems invasion arc'''),
    (51, 52, r'''Homeworld gems invasion arc'''),
    (52, 53, r'''Homeworld gems invasion arc'''),
    (52, 74, r'''"We were waiting for your birthday"'''),
    (48, 61, r'''Rose/Greg flashback arc'''),
    (61, 94, r'''Rose/Greg flashback arc'''),
    (52, 62, r'''Malachite arc'''),
    (62, 79, r'''Malachite arc'''),
    (52, 54, r'''Peridot hunt arc'''),
    (54, 60, r'''Peridot hunt arc'''),
    (60, 63, r'''Peridot hunt arc'''),
    (63, 67, r'''Peridot hunt arc'''),
    (67, 70, r'''Peridot hunt arc'''),
    (58, 68, r'''Connie sword training'''),
    (68, 95, r'''Connie sword training'''),
    (44, 60, r'''Gem mutants'''),
    (60, 68, r'''Gem mutants'''),
    (63, 64, r'''Sardonyx arc'''),
    (64, 67, r'''Sardonyx arc'''),
    (52, 70, r'''Cluster arc'''),
    (70, 71, r'''Cluster arc'''),
    (60, 71, r'''Gem Mutants'''),
    (71, 72, r'''Cluster arc'''),
    (72, 73, r'''Cluster arc'''),
    (13, 75, r'''Steven's age fluctuation'''),
    (73, 76, r'''Cluster arc'''),
    (72, 77, r'''Peridot's giant robot'''),
    (76, 77, r'''Peridot/Diamond communicator arc'''),
    (76, 79, r'''Cluster arc'''),
    (79, 80, r'''Cluster arc'''),
    (60, 80, r'''Gem Mutants'''),
    (81, 82, r'''Lapis/Peridot barn arc.'''),
    (82, 83, r'''Rubies arc'''),
    (79, 93, r'''Jasper/Lapis arc'''),
    (93, 95, r'''Jasper arc'''),
    (95, 96, r'''Jasper arc'''),
    (96, 97, r'''Amethyst self-worth arc'''),
    (96, 100, r'''Jasper arc'''),
    (97, 100, r'''Amethyst self-worth arc'''),
    (100, 101, r'''Jasper arc'''),
    (83, 102, r'''Rubies arc'''),
    (102, 103, r'''Rubies arc'''),
    (103, 123, r'''Rubies arc - Navy'''),
    (48, 85, r'''Greg/Marty's contract'''),
    (85, 86, r'''Greg's fortune'''),
    ('98/99', 130, r'''RQ killed PD arc - Breaking Point'''),
    ('98/99', 150, r'''Bismuth arc'''),
    (101, 102, r'''RQ killed PD arc'''),
    (102, 130, r'''RQ killed PD arc'''),
    (101, 105, r'''Smoky Quartz arc'''),
    (114, 115, r'''Zoo arc'''),
    (115, 116, r'''Zoo arc'''),
    (116, 117, r'''Zoo arc'''),
    (117, 118, r'''Zoo arc'''),
    (115, 119, r'''Crystal Gems' absence'''),
    (124, 153, r'''Pink's ship'''),
    (44, 125, r'''List of humans Steven gave Peridot'''),
    (125, 126, r'''Disappearing townies arc'''),
    (126, 127, r'''Disappearing townies arc'''),
    (127, 128, r'''Disappearing townies arc'''),
    (128, 133, r'''Townies' concern with handling of gem events'''),
    (128, 129, r'''Steven/Lars on Homeworld arc'''),
    (129, 130, r'''Steven/Lars on Homeworld arc'''),
    (130, 131, r'''Steven/Lars on Homeworld arc'''),
    (131, 132, r'''Steven/Lars on Homeworld arc'''),
    (128, 133, r'''Steven/Connie fight arc'''),
    (133, 134, r'''Steven/Connie fight arc'''),
    (134, 138, r'''Steven/Connie fight arc'''),
    (132, 139, r'''Lars/Off Colors arc'''),
    (133, 144, r'''Non-Mayor Dewey arc / Beach City preparation for gem events'''),
    (135, 136, r'''Lapis leaving arc - Peridot'''),
    (135, 145, r'''Lapis leaving arc'''),
    (139, 140, r'''Stranded arc'''),
    (137, 142, r'''Sadie Killer arc'''),
    (137, 144, r'''New Big Donut employee needed'''),
    (134, 146, r'''Pearl's unspeakable secret'''),
    (144, 145, r'''Ronaldo's lookout duty'''),
    (145, 146, r'''What Pearl knows'''),
    (146, 147, r'''RQ=PD aftermath arc - Sapphire'''),
    (146, 148, r'''RQ=PD aftermath arc - Amethyst'''),
    (146, 149, r'''RQ=PD aftermath arc - Ruby'''),
    (149, 150, r'''Ruby/Sapphire wedding arc'''),
    (80, '151/152', r'''Cluster arc'''),
    (145, '151/152', r'''Lapis leaving arc'''),
    (150, '151/152', r'''Ruby/Sapphire wedding arc'''),
    ('151/152', 153, r'''Diamonds/Steven arc'''),
    (153, 154, r'''Diamonds/Steven Homeworld arc'''),
    (154, 155, r'''Diamonds/Steven Homeworld arc'''),
    (155, 156, r'''Diamonds/Steven Homeworld arc''')
]

# Episodes that foreshadow a future episode
foreshadowing = [
    (1, 52, r'''Two shooting stars in OP when Garnet appears; Garnet fusion'''),
    (1, 12, r'''Temple statue; Existence of fusion'''),
    (1, 26, r'''Monsters have gems; Monsters are corrupted gems'''),
    (1, 7, r'''Bracelet in freezer; setting up for Connie intro'''),
    (1, 52, r'''Garnet having two gems; Garnet fusion'''),
    (1, 26, r'''Cookie cat song: "came to this planet from outer space"; Gems are aliens'''),
    (1, 146, r'''Cookie cat song: "pet for your tummy", "left his family behind"; RQ=PD'''),
    (1, 26, r'''Pearl: "Properties of this planet"; Gems are aliens'''),
    (2, 39, r'''Garnet adjusts glasses then announces only way to destroy Red Eye; Future vision'''),
    (2, 17, r'''"You've gotta know where it is... Like a cave dungeon"; Rose's armory'''),
    (2, 16, r'''"...or a cloud fortress"; Sky Arena'''),
    (3, 13, r'''"You should have seen it in its heyday"; Gems' age'''),
    (3, 26, r'''"Oasis for gems on earth"; Gems are aliens'''),
    (3, 39, r'''Garnet senses danger several times while adjusting glasses; Future vision'''),
    (4, 19, r'''Glimpse of Rose's Room'''),
    (4, 52, r'''Garnet has two door lights; Garnet fusion'''),
    (6, 9, r'''Amethyst shapeshifts briefly into Purple Puma'''),
    (7, 157, r'''Temple statue (Obsidian)'s sword visible in ocean'''), # Repeat from 26 not counted
    (8, 40, r'''"This was once a gem battlefield"; Gem rebellion'''),
    (8, 76, r'''Rose vs diamonds mural; Existence of diamond authority'''),
    (9, 146, r'''"that's why we're all here... to be wild and free... and make up nicknames"; RQ=PD'''),
    (10, 35, r'''Lion is pink; Lion belonging to Rose'''),
    (10, 146, r'''Pet lion; royalty symbolism; RQ=PD'''),
    (10, 40, r'''"We kept Amethyst"; Amethyst's origin'''),
    (11, 39, r'''"Heightened senses", third eye symbolism; Future vision'''),
    (11, 51, r'''"fighting a giant foot"; homeworld invasion hand ship'''),
    (13, 16, r'''"even if your [...] body's an illusion"; Gems' bodies being light constructs'''),
    (13, 146, r'''Crown/cape; royalty symbolism; RQ=PD'''),
    (14, 17, r'''Dogcopter 3 poster in background'''),
    (16, 26, r'''Gems poof same as monsters; Monsters are corrupted gems'''),
    (16, 39, r'''Garnet anticipates Steven raising his hand; Future vision'''),
    (16, 146, r'''Diamond on Holo-Pearl's chest; Pearl belonged to PD'''),
    (17, 132, r'''Lion can walk on water like Jesus; Lion was resurrected'''),
    (17, 146, r'''Giant penny; batman; secret identity; RQ=PD'''),
    (19, 35, r'''Tiny Floating Pink Whale has Rose's voice'''),
    (22, 26, r'''Flashforward of ocean disappearance'''),
    (22, 52, r'''Garnet playing keytar ('fusion' instrument); Garnet fusion'''),
    (23, 26, r'''Centipeedle humanoid stage while reforming; Monsters are corrupted gems'''),
    (23, 52, r'''"Shut down by the G-squad"; Garnet fusion'''),
    (28, 146, r'''Pink diamond on Pearl's spacesuit; Pearl belonged to PD'''),
    (31, 76, r'''"They're here to hollow out the earth"; Gem plans for Earth'''),
    (31, 76, r'''"It's all part of the great diamond authority"; Existence of Diamond Authority'''),
    (31, 140, r'''Upside down diamond on currency; Pink Diamond's design'''),
    (31, 146, r"Pearl's aversion to shape-shifting; Pearl's role in PD's 'shattering'"),
    (32, 52, r'''Ruby/Sapphire outlines briefly visible while Alexandrite unfusing; Garnet fusion'''),
    (33, 52, r'''"He's not ready to learn that I have secret animal friends"; Garnet fusion'''),
    (34, 146, r'''Watermelon crown; royalty symbolism; RQ=PD'''),
    (36, 40, r'''"They're coming back! I can't do this, not again!"; Gem rebellion'''),
    (36, 40, r'''"Preparing to locate and manually reactivate Kindergar-"; Kindergarten(s)'''),
    (37, 52, r'''"Fusion is really hard, even for us." "Not for me"; Garnet fusion'''),
    #(40, ???, r'''"Cookie Cat! [...] I never considered that you would be evil!"'''), # Not sure what to classify this as
    (43, 51, r'''Jasper appears on totem pole in U-Stor; Jasper'''),
    (43, 82, r'''"Season 3... that's when the uptight neighbors the Richingtons move next-door"; Peridot/Lapis moving into barn'''),
    (44, '111/112', r'''"I swear that's not his real name."; Steven/Greg's family name'''),
    (44, 153, r'''"But the records say that gems were wiped out on Earth"; Corrupting light was intended to destroy all Earth gems'''),
    (44, 155, r'''The Unfamiliar Familiar book; PD's new Pearl (unfamiliar 'familiar')'''),
    (45, 84, r'''Steven floats cartoonishly; Steven's floating power'''),
    (45, 146, r'''"If we win, we can never go home"; Rose not an earth Quartz; RQ=PD'''),
    (45, 72, r'''"My Pearl"; Pearls as servants'''),
    (45, 146, r'''"My Pearl"; Pearl belonged to Rose'''),
    (46, 153, r'''Clone Connie matches White Pearl's design'''),
    (48, 65, r'''Vidalia's name; Onion's mother'''),
    (51, 52, r'''"this shameless display" - Jasper, of Garnet; Garnet fusion'''),
    (51, 73, r'''"a puny overcooked runt" - Jasper, of Amethyst; Amethyst defective'''),
    (52, 76, r'''Diamond authority floor symbol; Existence of diamond authority'''),
    (58, 76, r'''Diamond authority symbol in arena; Existence of diamond authority'''),
    (58, 102, r'''Cracked PD symbol; death of PD'''),
    (59, 115, r'''Human zoo mentioned by ronaldo'''),
    (62, 153, r'''Both Pearl and Steven briefly do White Pearl's monochrome T-pose.'''),
    (63, 146, r'''Pink diamond on Sardonyx's feet; Pearl belonged to PD'''),
    (67, 72, r'''"I'm just a Pearl"; Pearls as servants'''),
    (69, 114, r'''"I can't help it if I make a scene / stepping out of my hot pink limousine"; PD/palanquin'''),
    #(69, ???, r'''"Maybe they'll juggle something sharp. I'm gonna have my phone ready in case someone gets hurt."; How White Pearl's eye got cracked?!''')),
    (70, 108, r'''Happy Bear/Sad Bunny; Mr. Smiley/Mr. Frowney'''),
    (72, 74, r'''"Welcome to Earth"'''),
    (72, 146, r'''"she looks like a fancy one"; Pearl belonged to PD"'''),
    (76, 140, r'''Moon base diamond throne is small; PD design'''),
    (76, 146, r'''PD symbols in Lion's warp; RQ=PD'''),
    (76, 146, r'''"We are literally walking in the footsteps of the diamonds."; RQ=PD'''),
    #(76, ???, r'''WD's gem being on her forehead; Pearl used to be WD's pearl'''),
    (81, 86, r'''Pepe's Burgers ad in background'''),
    (81, 92, r'''Yellow/blue/white-tinged nova shown in flashback; Source of corruption'''),
    (81, '98/99', r'''Bismuth briefly appears in flashback; Bismuth's identity'''),
    (84, 146, r'''Steven's skull appears on a pink diamond-shaped pillow; RQ=PD'''),
    (86, 118, r'''Greg/Pearl yellow/blue symbolism; YD/BD mourning PD'''),
    (94, 131, r'''"you better pray your space goddess' magic can bring people back from the dead"'''),
    ('98/99', 146, r'''Rose's sword couldn't shatter gems; PD still alive'''),
    ('98/99', 153, r'''Bismuth mentions defeating a Nephrite from a drop-ship; Nephrite's identity'''),
    (100, 118, r'''Carnelian and Skinny's exit holes described'''),
    (102, 134, r'''Pearl covering her mouth when details of PD's death are brought up'''),
    (102, 146, r"Eyeball claims to have witnessed RQ murder PD while currently being fooled by shapeshifting; Pearl's role in PD's 'shattering'"),
    (103, 146, r'''"That's more of a pinkish-red than a real Rose Quartz reddish-pink."; RQ=PD'''),
    (106, 114, r'''PD's palanquin appears in journal'''),
    (106, 132, r'''A non-magical lion with the same nose as Lion is seen in the flashback; Lion's origin'''),
    (110, 146, r'''Garbanzo fakes his own death; PD faking her death'''),
    (113, 146, r'''Baby Steven's clothes make diamond shape around his gem; RQ=PD'''),
    (115, 146, r'''"When I still served... Homeworld"; Pearl unwilling to reveal the gem she served; Pearl belonged to PD'''),
    (120, '151/152', r'''Lonely Arms video game image looks like Cluster/YD's ship arm wresting'''),
    (124, 146, r'''Pink's ship in desert where Rose stores her stuff; RQ=PD'''),
    (130, 146, r'''"Someone with supreme authority"; RQ=PD'''),
    (140, 146, r'''Steven has PD's memories; RQ=PD'''),
    (141, 146, r'''"Rose Quartz isn't real"; RQ=PD'''),
    (148, 149, r'''"Why would she be a cowboy?!"'''),
    (153, 155, r'''Gem on stomach; White Pearl originally belonged to PD''')
    #(154, ???, r'''Diamond secretions collected / Steven creating pebble; Diamond secretions used in injectors to create life''') # TODO when relevant
    #(156, ???, r'''War between CGs and homeworld, resolution?'''),
]

# Episodes that callback to a detail of a previous episode
# Reoccurences of the subject of a callback are ignored (e.g. the Crying Breakfast Friends cartoon
# appears many times throughout the show but is only recorded as a callback the first time it is
# reused)
callbacks = [
    (10, 6, r'''Cat fingers pic on Ronaldo's blog'''),
    (13, 1, r'''Lion Lickers freezer, Cookie Cat in Amethyst's junk'''),
    (15, 11, r'''Moped Onion won at arcade'''),
    (19, 2, r'''Greg's golf clubs'''),
    (19, 5, r'''Frybo'''),
    (19, 7, r'''"He was incredible" flashback'''),
    (21, 9, r'''Tiger Millionaire/Purple Puma poster in Big Donut break room'''),
    (22, 1, r'''Passed through while time travelling'''),
    (22, 19, r'''Passed through while time travilling'''),
    (25, 3, r'''Variation on Lapis' theme was heard in Sea spire'''),
    (26, 2, r'''"What's that thing you always say about the pork chops and the hotdogs?"'''),
    (26, 9, r'''Amethyst transforms into Purple Puma'''),
    (26, 16, r'''"I hate fighting me"'''),
    (28, 1, r'''Crying Breakfast Friends cartoon'''),
    (31, 2, r'''Pieces of red eye'''),
    (31, 11, r'''Drill monster holes'''),
    (31, 14, r'''Magic moss flowers'''),
    (34, 30, r'''Sadie's scar'''),
    #(35, 1, r'''Lion Lickers'''), # Repeat Lion Lickers callback
    (35, 14, r'''Steven/Lars' high five.'''),
    (35, 17, r'''Dogcopter'''),
    (35, 21, r'''VCR in Big Donut'''),
    (36, 12, r'''Steven Jr'''),
    (38, 8, r'''Trials resemble those in pyramid temple'''),
    (38, 36, r'''Ceiling hole from robonoid'''),
    (39, 25, r'''M.C. Bear Bear (new doll after Pearl stabbed old one)'''),
    (42, 23, r'''Shooting Star'''),
    (42, 32, r'''Steven having been grounded from TV'''),
    (43, 2, r'''Broken picture frame'''),
    (44, 2, r'''Peridot mentions Red Eye'''),
    (44, 7, r'''"Funky flow"'''),
    (46, 19, r'''Rose's Room, Tiny Floating Pink Whale'''),
    (46, 44, r'''Spirit Morph Saga book series'''),
    (47, 2, r'''T-shirt cannon'''),
    (49, 19, r'''Wailing Stone'''),
    (49, 26, '''The album cover Greg mentioned having a great idea for'''),
    (50, 45, r'''Quartizine trio'''),
    (51, 2, r'''Gems' telescope'''),
    (55, 39, r'''Wasps from Steven's imagination reappear'''),
    (55, 33, r'''Hopper appears in video game'''),
    (56, 12, r'''Garnet's swimming goggles'''),
    (57, 18, r'''Fashion magazine'''),
    (57, 25, r'''CPR dummy'''),
    (57, 40, r'''No Home Boys book'''),
    (58, 16, r'''Gem runes in backgrounds'''),
    (58, 28, r'''Carvings on wall match Galaxy Warp layout'''),
    (59, 10, r'''"Steven's Pregnant?!" joke referenced'''),
    (60, 57, r'''Note on fridge referencing Amethyst's consumption of engine oil'''),
    (60, 44, r'''Steven imitates robonoids' walking sound.'''),
    (64, 6, r'''"I don't like those brushes, they feel weird on your fur."'''),
    (66, 56, r'''"Humans aren't very good swimmers"; Jamie imitating Garnet's prior line'''),
    (70, 23, r'''Bubbled Chaaaaps'''),
    (70, 64, r'''"What's with you guys and making me pee outside!?"'''),
    (72, 28, r'''UUU Space Travel'''),
    (73, 70, r'''"Keep her outside on a leash?"'''),
    (74, 52, r''''Stronger than You' chords reprised in lullaby'''),
    (75, 2, r'''Song 'Let me Drive My Van into Your Heart' in background'''),
    (75, 13, r'''Steven's birthday suit'''),
    (75, 24, r'''Durian juice'''),
    (75, 61, r'''Connie/Greg "human beings" high five'''),
    (75, 68, r'''Connie no longer wearing fake glasses'''),
    (78, 70, r'''Peridot thinking a 'shirt' is any piece of clothing'''),
    (80, 78, r'''"Wow, thanks"'''),
    (81, 25, r'''Lapis/Steven blowing raspberries'''),
    (81, 28, r'''Caterpillar sleeping bag'''),
    (82, 78, r'''Camp Pining Hearts'''),
    (82, 80, r'''Drill hole reused to make pool'''),
    (83, 26, r'''"Bob"'''),
    (86, 16, r'''Sanic figurine'''),
    (86, 19, r'''Golf Quest Mini game'''),
    (86, 42, r'''Greg self-describes as "cherry man"'''),
    (86, 43, r'''Passions of Xanxor book'''),
    (86, 48, r''''Comet' theme reprised in Pepe's Burgers jingle'''),
    (87, 6, r'''Steven creating a cat finger'''),
    (89, 81, r'''Himitsu car company'''),
    (91, 10, r'''"Sorry for using the same pun twice"'''),
    (94, 43, r'''Li'l Butler'''),
    (94, 61, r'''The Philosophy Majors album'''),
    (95, 58, r''''Do It for Her' lyrics mentioned'''),
    (96, 60, r'''Pretty Hairstylist magazine'''),
    (96, 62, r'''"Bungacowa"'''),
    (96, 86, r'''Sadie humming Pepe's Burgers jingle'''),
    (97, 16, r'''"Boomerang shield"; Lonely Blade'''),
    #(97, 16, r'''Lonely Blade appears in video game'''), # Duplicate Lonely Blade reference
    ('98/99', 16, r'''Pearl having learnt that movies don't have to make sense'''),
    (100, 87, r'''Alien plush'''),
    (105, 74, r'''Garnet never asks questions; Rose's "No more questions"'''),
    (106, 56, r'''Jamie's "drama zone"'''),
    (107, 49, r'''"Hold the phone. Now give the phone to me"'''),
    (108, 8, r'''Steven's Funland ban'''),
    (109, 50, r'''The Ocean Town disaster'''),
    (113, 42, r'''Greg half-singing about his carabiner'''),
    (113, 49, r'''Greg: "I'm not that far away", to Steven'''),
    (113, 75, r'''"box made to look like it's wrapped"'''),
    (114, 48, r'''"Keep Out <i>Please</i>" sign'''),
    (114, 86, r'''Model sheets from Mr Greg shown in-show'''),
    (115, 103, r'''Navies seen floating in space'''),
    (119, 70, r'''Peridot trying to flush herself down the toilet'''),
    (119, 78, r'''Peridot mimicking Garnet's thumbs up'''),
    (120, 107, r'''Connie using mindful meditation'''),
    (122, 61, r''''mics are expensive' remark'''),
    (123, '111/112', r'''Inability to talk to corn'''),
    (124, 17, r'''Desert lizard, originally mentioned as "who knows where [Lion] got that.'''),
    (126, 14, r'''"It's all happening! Lars and the Cool Kids"; episode title'''),
    (126, 47, r'''Guitar Dad shirt'''),
    (126, 110, r'''Painting Vidalia was making of Yellowtail, completed on wall.'''),
    (127, 3, r''''Hey, Mr Postman' song'''),
    (128, 37, r'''"'Alone Together' song is Connie's ringtone'''),
    (133, 58, r''''How to Talk to People' book'''),
    (133, 22, r'''"Speech-a-Palooza"/Beach-a-Palooza'''),
    (134, 90, r'''Koala Princess dvds'''),
    (135, 34, r'''Onion wearing straw hat; "is that my hat?"'''),
    (135, 82, r'''"smaller than average lake"'''),
    (138, 75, r'''Pink shirt Connie gave Steven'''),
    (138, 109, r'''Sugar Shock Shutdown'''),
    (139, 37, r'''Stevonnie as "an experience"'''),
    (142, 109, r'''Mystery Girl cameos in background'''),
    (145, 25, r''''Mirror Gem' background music reprised when Lapis gets upset'''),
    (146, 6, r'''Gem sloop stored in Pearl's gem'''),
    (146, 56, r'''Sea Pals stored in Pearl's gem'''),
    (146, 97, r'''Pearl point stored in Pearl's gem'''),
    (146, 109, r'''Mystery Girl's \# in Pearl's gem'''),
    (150, 11, r'''Meat Beat Mania game'''),
    ('151/152', 4, r'''Together Breakfast as wedding cake'''),
    ('151/152', 86, r'''Greg/Pearl/Steven's tailor-made suits'''),
    ('151/152', 113, r'''Razor Garnet gifted baby Steven'''),
    ('151/152', 145, "You could drop the barn on the beach"),
    (156, 7, r'''Steven failing to convey something with a drawing, which is better explained in words''')
]
