#! /usr/bin/env python3
# -*- coding: utf-8 -*-

from show_continuity import *

'''Continuity data on the show Adventure Time.'''

show = Show(
    title='Adventure Time',
    seasons={1: dict(num_eps=26, color='#804060'),
             2: dict(num_eps=26, color='#804060'),
             3: dict(num_eps=25, color='#804060'),
             4: dict(num_eps=26, color='#804060'),
             5: dict(num_eps=51, color='#804060'),
             6: dict(num_eps=43, color='#804060'),
             7: dict(num_eps=25, color='#804060'),
             8: dict(num_eps=27, color='#804060'),
             9: dict(num_eps=14, color='#804060'),
             10: dict(num_eps=13, color='#804060')},
    episodes={
        1: 'Slumber Party Panic',
        2: 'Trouble in Lumpy Space',
        3: 'Prisoners of Love',
        4: 'Tree Trunks',
        5: 'The Enchiridion!',
        6: 'The Jiggler',
        7: 'Ricardio the Heart Guy',
        8: 'Business Time',
        9: 'My Two Favorite People',
        10: 'Memories of Boom Boom Mountain',
        11: 'Wizard',
        12: 'Evicted!',
        13: 'City of Thieves',
        14: "The Witch's Garden",
        15: 'What Is Life?',
        16: 'Ocean of Fear',
        17: 'When Wedding Bells Thaw',
        18: 'Dungeon',
        19: 'The Duke',
        20: 'Freak City',
        21: 'Donny',
        22: 'Henchman',
        23: 'Rainy Day Daydream',
        24: 'What Have You Done?',
        25: 'His Hero',
        26: 'Gut Grinder',
        27: 'It Came from the Nightosphere',
        28: 'The Eyes',
        29: 'Loyalty to the King',
        30: 'Blood Under the Skin',
        31: 'Storytelling',
        32: 'Slow Love',
        33: 'Power Animal',
        34: 'Crystals Have Power',
        35: 'The Other Tarts',
        36: "To Cut a Woman's Hair",
        37: 'The Chamber of Frozen Blades',
        38: 'Her Parents',
        39: 'The Pods',
        40: 'The Silent King',
        41: 'The Real You',
        42: 'Guardians of Sunshine',
        43: 'Death in Bloom',
        44: 'Susan Strong',
        45: 'Mystery Train',
        46: 'Go with Me',
        47: 'Belly of the Beast',
        48: 'The Limit',
        49: 'Video Makers',
        50: 'Mortal Folly',
        51: 'Mortal Recoil',
        52: 'Heat Signature',
        53: 'Conquest of Cuteness',
        54: 'Morituri Te Salutamus',
        55: 'Memory of a Memory',
        56: 'Hitman',
        57: 'Too Young',
        58: 'The Monster',
        59: 'Still',
        60: 'Wizard Battle',
        61: 'Fionna and Cake',
        62: 'What Was Missing',
        63: 'Apple Thief',
        64: 'The Creeps',
        65: 'From Bad to Worse',
        66: 'Beautopia',
        67: 'No One Can Hear You',
        68: 'Jake vs. Me-Mow',
        69: 'Thank You',
        70: 'The New Frontier',
        '71/72': 'Holly Jolly Secrets',
        73: "Marceline's Closet",
        74: 'Paper Pete',
        75: 'Another Way',
        76: 'Ghost Princess',
        77: "Dad's Dungeon",
        78: 'Incendium',
        79: 'Hot to the Touch',
        80: 'Five Short Graybles',
        81: 'Web Weirdos',
        82: 'Dream of Love',
        83: 'Return to the Nightosphere',
        84: "Daddy's Little Monster",
        85: 'In Your Footsteps',
        86: 'Hug Wolf',
        87: 'Princess Monster Wife',
        88: 'Goliad',
        89: 'Beyond This Earthly Realm',
        90: 'Gotcha!',
        91: 'Princess Cookie',
        92: 'Card Wars',
        93: 'Sons of Mars',
        94: 'Burning Low',
        95: 'BMO Noire',
        96: 'King Worm',
        97: 'Lady & Peebles',
        98: 'You Made Me',
        99: 'Who Would Win',
        100: 'Ignition Point',
        101: 'The Hard Easy',
        102: 'Reign of Gunters',
        103: 'I Remember You',
        104: 'The Lich',
        105: 'Finn the Human',
        106: 'Jake the Dog',
        107: 'Five More Short Graybles',
        108: 'Up a Tree',
        109: 'All the Little People',
        110: 'Jake the Dad',
        111: 'Davey',
        112: 'Mystery Dungeon',
        113: 'All Your Fault',
        114: 'Little Dude',
        115: 'Bad Little Boy',
        116: 'Vault of Bones',
        117: 'The Great Bird Man',
        118: 'Simon & Marcy',
        119: 'A Glitch Is a Glitch',
        120: 'Puhoy',
        121: 'BMO Lost',
        122: 'Princess Potluck',
        123: 'James Baxter the Horse',
        124: 'Shh!',
        125: 'The Suitor',
        126: "The Party's Over, Isla de Señorita",
        127: 'One Last Job',
        128: 'Another Five More Short Graybles',
        129: 'Candy Streets',
        130: 'Wizards Only, Fools',
        131: 'Jake Suit',
        132: 'Be More',
        133: 'Sky Witch',
        134: 'Frost & Fire',
        135: 'Too Old',
        136: 'Earth & Water',
        137: 'Time Sandwich',
        138: 'The Vault',
        139: 'Love Games',
        140: 'Dungeon Train',
        141: 'Box Prince',
        142: 'Red Starved',
        143: 'We Fixed a Truck',
        144: 'Play Date',
        145: 'The Pit',
        146: 'James',
        147: 'Root Beer Guy',
        148: 'Apple Wedding',
        149: 'Blade of Grass',
        150: 'Rattleballs',
        151: 'The Red Throne',
        152: 'Betty',
        153: 'Bad Timing',
        '154/155': 'Lemonhope',
        156: "Billy's Bucket List",
        157: 'Wake Up',
        158: 'Escape from the Citadel',
        159: 'James II',
        160: 'The Tower',
        161: 'Sad Face',
        162: 'Breezy',
        163: 'Food Chain',
        164: 'Furniture & Meat',
        165: 'The Prince Who Wanted Everything',
        166: 'Something Big',
        167: 'Little Brother',
        168: 'Ocarina',
        169: 'Thanks for the Crabapples, Giuseppe!',
        170: 'Princess Day',
        171: 'Nemesis',
        172: 'Joshua & Margaret Investigations',
        173: 'Ghost Fly',
        174: "Everything's Jake",
        175: 'Is That You?',
        176: 'Jake the Brick',
        177: 'Dentist',
        178: 'The Cooler',
        179: 'The Pajama War',
        180: 'Evergreen',
        181: 'Astral Plane',
        182: 'Gold Stars',
        183: 'The Visitor',
        184: 'The Mountain',
        185: 'Dark Purple',
        186: 'The Diary',
        187: 'Walnuts & Rain',
        188: 'Friends Forever',
        189: 'Jermaine',
        190: 'Chips & Ice Cream',
        191: 'Graybles 1000+',
        192: 'Hoots',
        193: 'Water Park Prank',
        194: 'You Forgot Your Floaties',
        195: 'Be Sweet',
        196: 'Orgalorg',
        197: 'On the Lam',
        198: 'Hot Diggity Doom',
        199: 'The Comet',
        200: 'Bonnie & Neddy',
        201: 'Varmints',
        202: 'Cherry Cream Soda',
        203: 'Mama Said',
        204: 'Football',
        205: 'Stakes Part 1: Marceline the Vampire Queen',
        206: 'Stakes Part 2: Everything Stays',
        207: 'Stakes Part 3: Vamps About',
        208: 'Stakes Part 4: The Empress Eyes',
        209: 'Stakes Part 5: May I Come In?',
        210: 'Stakes Part 6: Take Her Back',
        211: 'Stakes Part 7: Checkmate',
        212: 'Stakes Part 8: The Dark Cloud',
        '213/214': 'The More You Moe, the Moe You Know',
        215: 'Summer Showers',
        216: 'Angel Face',
        217: 'President Porpoise Is Missing!',
        218: 'Blank-Eyed Girl',
        219: 'Bad Jubies',
        220: "King's Ransom",
        221: 'Scamps',
        222: 'Crossover',
        223: 'The Hall of Egress',
        224: 'Flute Spell',
        225: 'The Thin Yellow Line',
        226: 'Broke His Crown',
        227: "Don't Look",
        228: 'Beyond the Grotto',
        229: 'Lady Rainicorn of the Crystal Dimension',
        230: 'I Am a Sword',
        231: 'Bun Bun',
        232: 'Normal Man',
        233: 'Elemental',
        234: 'Five Short Tables',
        235: 'The Music Hole',
        236: 'Daddy-Daughter Card Wars',
        237: 'Preboot',
        238: 'Reboot',
        239: 'Two Swords',
        240: 'Do No Harm',
        241: 'Wheels',
        242: 'High Strangeness',
        243: 'Horse and Ball',
        244: 'Jelly Beans Have Power',
        245: 'Islands Part 1: The Invitation',
        246: 'Islands Part 2: Whipple the Happy Dragon',
        247: 'Islands Part 3: Mysterious Island',
        248: 'Islands Part 4: Imaginary Resources',
        249: 'Islands Part 5: Hide and Seek',
        250: 'Islands Part 6: Min & Marty',
        251: 'Islands Part 7: Helpers',
        252: 'Islands Part 8: The Light Cloud',
        253: 'Orb',
        254: 'Elements Part 1: Skyhooks',
        255: 'Elements Part 2: Bespoken For',
        256: 'Elements Part 3: Winter Light',
        257: 'Elements Part 4: Cloudy',
        258: 'Elements Part 5: Slime Central',
        259: 'Elements Part 6: Happy Warrior',
        260: 'Elements Part 7: Hero Heart',
        261: 'Elements Part 8: Skyhooks II',
        262: 'Abstract',
        263: 'Ketchup',
        264: 'Fionna and Cake and Fionna',
        265: 'Whispers',
        266: 'Three Buckets',
        267: 'The Wild Hunt',
        268: 'Always BMO Closing',
        269: 'Son of Rap Bear',
        270: 'Bonnibel Bubblegum',
        271: 'Seventeen',
        272: 'Ring of Fire',
        273: 'Marcy & Hunson',
        274: 'The First Investigation',
        275: 'Blenanas',
        276: 'Jake the Starchild',
        277: 'Temple of Mars',
        278: 'Gumbaldia',  # TODO: 279 is a special ep but season coloring doesnt currently handle seasons not being
                           #       continuous well. Moving to episodes being stored in their season's dict will fix this
        '280-283': 'Come Along with Me'})

show.plot_threads = [
    #(3, ?, Plot.REFERENTIAL, "The Cosmic Owl"),
    (22, 27, Plot.CAUSAL, "Finn/Marceline having become friends"),
    (4, 34, Plot.CAUSAL, "Tree Trunks in the crystal dimension"),
    #(25, ?, Plot.REFERENTIAL, "Billy, the Lich"),
    (50, 51, Plot.SERIAL, "Lich possessing Bubblegum"),
    (51, 57, Plot.CAUSAL, "Bubblegum having reverted to younger self"),
    (36, 62, Plot.REFERENTIAL, "Finn's lock of PB's hair"),
    (1, 65, Plot.CAUSAL, "PB's experiments with candy zombies"),
    (44, 66, Plot.CAUSAL, "Susan Strong"),
    (27, '71/72', Plot.REFERENTIAL, "Fry song"),
    (5, 75, Plot.CAUSAL, "The Enchiridion"),
    (36, 78, Plot.REFERENTIAL, "Finn's lock of PB's hair"),
    (78, 79, Plot.SERIAL, "Finn's crush on Flame Princess"),
    (27, 84, Plot.CAUSAL, "Finn knowing how to portal to the Nightosphere"),
    (83, 84, Plot.SERIAL, "Rescuing Marcline from the Nightosphere"),
    (5, 85, Plot.CAUSAL, "The Lich stealing the Enchiridion from Finn"),
    (79, 94, Plot.CAUSAL, "Finn/Flame Princess' relationship"),
    (12, 96, Plot.CAUSAL, "Worms/King Worm infesting the tree house during Marceline's stay"),
    (16, 96, Plot.REFERENTIAL, "Fear Feaster living in Finn"),
    (50, 96, Plot.REFERENTIAL, "Finn's fear of the Lich"),
    (64, 96, Plot.REFERENTIAL, "Finn's fear of the ghost (Shoko)"),
    (7, 97, Plot.CAUSAL, "Ricardio's revenge / Ricardio as Ice King's heart"),
    (79, 100, Plot.CAUSAL, "Finn/Flame Princess' relationship"),
    (17, 102, Plot.REFERENTIAL, "The Demonic Wishing Eye"),
    (79, 102, Plot.REFERENTIAL, "Finn/Flame Princess' relationship"),
    (27, 103, Plot.REFERENTIAL, "Fry song"),
    ('71/72', 103, Plot.CAUSAL, "Ice King's past arc"),
    (85, 104, Plot.CAUSAL, "The Lich having obtained the Enchiridion"),
    (104, 105, Plot.SERIAL, "The Lich and the portal"),
    (105, 106, Plot.SERIAL, "The Lich and the portal"),
    (61, 112, Plot.CAUSAL, "Ice King's Fionna and Cake fan fiction"),
    (98, 113, Plot.REFERENTIAL, "Lemongrab 2"),
    (61, 115, Plot.CAUSAL, "Ice King's Fionna and Cake fan fiction"),
    (100, 116, Plot.CAUSAL, "Flame Princess' dad telling her she's evil"),
    (40, 117, Plot.CAUSAL, "The goblin king Finn deposed"),
    (103, 118, Plot.CAUSAL, "Simon/Marceline's past arc"),
    (79, 120, Plot.CAUSAL, "Finn/Flame Princess' relationship"),
    (40, 131, Plot.REFERENTIAL, "The Jake suit"),
    (79, 131, Plot.REFERENTIAL, "Finn/Flame Princess' relationship"),
    (55, 133, Plot.CAUSAL, "Ash having stolen Marceline's stuffed animal"),
    (79, 134, Plot.CAUSAL, "Finn/Flame Princess' relationship"),
    (98, 134, Plot.REFERENTIAL, "Lemongrab 2"),
    (134, 135, Plot.CAUSAL, "Finn/Flame Princess' break-up"),
    (134, 136, Plot.CAUSAL, "Finn/Flame Princess' break-up"),
    (64, 138, Plot.CAUSAL, "Finn's nightmares of when Shoko haunted him"),
    (134, 144, Plot.CAUSAL, "Ice King living with Finn/Jake"),
    (144, 145, Plot.SERIAL, "Jake having been kidnapped"),
    (82, 148, Plot.CAUSAL, "Tree Trunks/Mr. Pig's relationship"),
    (145, 149, Plot.CAUSAL, "Finn's sword having broken"),
    (136, 151, Plot.CAUSAL, "The imprisoned Flame King, Finn/Flame Princess' past relationship"),
    ('71/72', 152, Plot.CAUSAL, "Simon/Betty arc"),
    (103, 152, Plot.CAUSAL, "Simon/Marceline's past arc"),  # 118?
    (133, 152, Plot.REFERENTIAL, "Hambo"),
    (134, '154/155', Plot.CAUSAL, "Lemonhope's expulsion from the lemon kingdom"),
    (104, 156, Plot.CAUSAL, "Billy's death"),
    (106, 157, Plot.CAUSAL, "The Lich trapped in the Time Room"),
    (156, 157, Plot.SERIAL, "Revelation that Finn's father is alive"),
    (148, 158, Plot.REFERENTIAL, "Tree Trunks/Mr. Pig's marriage"),
    (149, 158, Plot.CAUSAL, "The curse of the grass sword"),
    (157, 158, Plot.SERIAL, "The imprisoned Lich / Finn & Jake breaking into the Citadel"),
    (146, 159, Plot.CAUSAL, "James' obsession with getting cloned / The original James' survival"),
    (158, 160, Plot.CAUSAL, "Finn's missing arm"),
    (158, 162, Plot.CAUSAL, "Finn's flower-arm"),
    (61, 165, Plot.CAUSAL, "Ice King's Fionna and Cake fan fiction"),
    (48, 166, Plot.REFERENTIAL, "Ancient Psychic Tandem War Elephant"),
    (133, 166, Plot.CAUSAL, "Maja using the T-shirt PB gave her for a ritual"),
    (147, 166, Plot.REFERENTIAL, "Root Beer Guy having become captain of the Banana Guards"),
    (12, 168, Plot.REFERENTIAL, "Marceline owning the Tree House's deed"),
    (157, 175, Plot.CAUSAL, "Prism's death"),
    (9, 177, Plot.CAUSAL, "Tiffany's rivalry with Finn"),
    # Technically causal to all Ice King episodes but doesn't matter for our seriality metric (by design)
    (180, 3, Plot.CAUSAL, "Ice Crown's origin"),
    (158, 181, Plot.CAUSAL, "Martin having escaped prison"),
    (158, 182, Plot.CAUSAL, "Sweet P's origin"),
    (181, 183, Plot.CAUSAL, "Martin crash landing on Earth"),
    (152, 194, Plot.CAUSAL, "Betty wanting to cure Simon"),
    (183, 197, Plot.CAUSAL, "Martin back in space"),
    (192, 198, Plot.CAUSAL, "Cosmic Owl causing PB's dream to come true"),
    (196, 198, Plot.CAUSAL, "Gunter's true identity as Orgalorg"),
    (158, 199, Plot.CAUSAL, "Finn's grass arm curse"),
    (197, 199, Plot.CAUSAL, "Martin and the Moth"),
    (198, 199, Plot.SERIAL, "The Catalyst Comet, Orgalorg"),
    (198, 200, Plot.CAUSAL, "King of Ooo's reign"),
    (198, 201, Plot.CAUSAL, "PB having been deposed"),
    (166, 202, Plot.CAUSAL, "Root Beer Guy's death"),
    (198, 203, Plot.CAUSAL, "King of Ooo's reign"),
    (205, 206, Plot.SERIAL, "Marceline trapped in sunlight"),
    (206, 207, Plot.SERIAL, "Resurrected vampires"),
    (207, 208, Plot.CAUSAL, "The resurrected vampires: The Empress"),
    (207, 209, Plot.CAUSAL, "The resurrected vampires: Hierophant"),
    (208, 209, Plot.CAUSAL, "The group teaming up to hunt the vampires"),
    (207, 210, Plot.CAUSAL, "The resurrected vampires: The Moon"),
    (209, 210, Plot.SERIAL, "Marceline poisoned"),
    (207, 211, Plot.CAUSAL, "The resurrected vampires: The Vampire King"),
    (208, 211, Plot.CAUSAL, "The group teaming up to hunt the vampires"),
    (198, 212, Plot.CAUSAL, "The King of Ooo's reign / PB deposed"),
    (211, 212, Plot.SERIAL, "The Dark Cloud"),
    (132, '213/214', Plot.REFERENTIAL, "The MO factory"),
    (194, 220, Plot.CAUSAL, "Betty using magic to cure Simon"),
    (106, 222, Plot.CAUSAL, "Farmworld Finn and the Lich"),
    (220, 226, Plot.CAUSAL, "Betty's malware in the ice crown"),
    (175, 230, Plot.REFERENTIAL, "The finn-sword"),
    (136, 231, Plot.CAUSAL, "Finn/Flame Princess' relationship / the imprisoned Flame King"),
    (181, 232, Plot.CAUSAL, "Glob stuck in space after saving Mars"),
    (194, 232, Plot.CAUSAL, "Magic Man having lost his magic"),
    (61, 234, Plot.CAUSAL, "Ice King's Fionna and Cake fan fiction"),
    (66, 237, Plot.CAUSAL, "Susan Strong and Beautopia"),
    (158, 238, Plot.CAUSAL, "Finn's grass sword / arm"),
    (230, 238, Plot.CAUSAL, "Finn-sword broken with a piece of the grass sword in it"),
    (237, 238, Plot.CAUSAL, "Susan's cybernetics / escaped electric eel"),
    (238, 239, Plot.SERIAL, "Grass Finn"),
    (238, 240, Plot.CAUSAL, "Susan's injury"),
    (239, 240, Plot.CAUSAL, "Grass Finn living with Finn/Jake"),
    (123, 243, Plot.REFERENTIAL, "James Baxter"),
    (233, 244, Plot.CAUSAL, "The princess' elemental powers awakening"),
    (238, 245, Plot.CAUSAL, "Signal sent by Susan's implant"),
    (245, 246, Plot.SERIAL, "Journey to find the source of the robotic craft"),
    (245, 247, Plot.SERIAL, "Journet to find the source of the robotic craft"),
    (247, 248, Plot.SERIAL, "The group split up, BMO in a simulator"),
    (248, 249, Plot.SERIAL, "Searching for Susan"),
    (249, 250, Plot.SERIAL, "Susan having remembered her past"),
    (250, 251, Plot.SERIAL, "Journey to Founder's Island, Finn's origin"),
    (251, 252, Plot.SERIAL, "Minerva trying to convince Finn to stay on Founder's Island"),
    (252, 253, Plot.CAUSAL, "Returning from Founder's Island"),
    (244, 254, Plot.CAUSAL, "PB having gotten closer to her elemental nature / Patience St. Pim's scheme"),
    (194, 255, Plot.CAUSAL, "Betty trying to save Simon / Betty's magic powers"),  # 254?
    (254, 255, Plot.SERIAL, "Ooo's changes"),
    (194, 256, Plot.CAUSAL, "Betty trying to use magic to save Simon"),
    (222, 256, Plot.CAUSAL, "Finn having acquired the Farmworld Enchiridion"),
    (255, 256, Plot.SERIAL, "Rescuing Betty"),
    (256, 257, Plot.SERIAL, "Forming a plan to fix Ooo"),
    (257, 258, Plot.SERIAL, "Collecting the princess' gems to fix Ooo"),
    (257, 259, Plot.SERIAL, "Collecting the princess' gems to fix Ooo"),
    (259, 260, Plot.SERIAL, "Finn having turned into a fire person / war between the Candy and Fire Kingdoms"),
    (260, 261, Plot.SERIAL, "Betty having stolen the gems / Finn trapped in the Candy Kingdom"),
    (261, 262, Plot.CAUSAL, "Jake having turned blue like his shape-shifter parent"),
    (206, 263, Plot.REFERENTIAL, "Marceline's mother"),
    (245, 263, Plot.CAUSAL, "Story from the boat trip in Islands"),
    (254, 263, Plot.CAUSAL, "Story of how Patience St. Pim brainwashed PB"),
    (61, 264, Plot.CAUSAL, "Ice King's Fionna and Cake fan fiction"),
    (158, 265, Plot.CAUSAL, "Sweet P/The Lich"),
    (222, 265, Plot.CAUSAL, "The Lich's severed hand"),
    (240, 265, Plot.CAUSAL, "Fern's existential crisis arc"),
    (239, 266, Plot.CAUSAL, "Finn's robotic arm"),
    (261, 266, Plot.CAUSAL, "Gumbald restored to his original self when LSP fixed Ooo"),
    (265, 266, Plot.CAUSAL, "Fern's decision to become Finn"),
    (224, 267, Plot.CAUSAL, "Finn/Huntress Wizard's relationship"),
    (266, 267, Plot.CAUSAL, "Finn's guilt over Fern's death / Gumbald's monster"),
    (266, 268, Plot.CAUSAL, "Gumbald's schemes"),
    (231, 269, Plot.CAUSAL, "Finn/Flame Princess' hobby of rapping together / FP and Flame King's relationship"),
    (44, 270, Plot.REFERENTIAL, "Gumbald having cut down the taffy trees"),
    (268, 270, Plot.CAUSAL, "Silver cup given by Gumbald"),
    (267, 271, Plot.CAUSAL, "Gumbald resurrecting Fern"),
    (172, 274, Plot.CAUSAL, "The events of Jake's birth"),
    (274, 275, Plot.CAUSAL, "Jake's disappearance"),
    (274, 276, Plot.SERIAL, "Jake's disappearance"),
    (194, 277, Plot.CAUSAL, "Margles having been taken by GOLB"),
    (261, 277, Plot.CAUSAL, "Betty on Mars"),
    (276, 277, Plot.SERIAL, "Jake stranded in space"),
    (271, 278, Plot.SERIAL, "The brewing war against Gumbald"),
    (253, '280-283', Plot.CAUSAL, "The Nightmare Juice"),
    (271, '280-283', Plot.CAUSAL, "Finn and Fern's rivalry"),
    (277, '280-283', Plot.CAUSAL, "Betty's plan to save Simon and Margles"),
    (278, '280-283', Plot.SERIAL, "The war against Gumbald"),
]

show.foreshadowing = [
    (3, '71/72', Foreshadowing.MAJOR, '''"big nerd"; Ice King used to be an antiquarian and wore glasses'''),
    #(8, 103, Foreshadowing.MAJOR, "Frozen business men; Ooo is a post-apocalyptic world"),
    (23, 25, Foreshadowing.MINOR, "Cosmic Gauntlet closely resembles Billy's gauntlet"),
    #(25, 36, Foreshadowing.MINOR, '''"who offered him her hair"; PB letting Finn take some of her hair'''),
    (27, 196, Foreshadowing.MAJOR, '''"you are by far the most evil thing I've encountered"; Gunter is Orgalorg'''),
    (34, 93, Foreshadowing.MAJOR, '''"If I had a penny for every time someone went crazy, hopped up on magic'''
                                  + ''' energy... I'd be Abraham Lincoln"; Magic Man, Lincoln's penny.'''),
    (44, 158, Foreshadowing.MAJOR, '''"grass can't hurt you"; Finn losing his arm to the grass sword'''),
    ('71/72', 82, Foreshadowing.MAJOR, "Tree Trunks/Pig shown together; Tree Trunks/Pig's relationship"),
    ('71/72', 103, Foreshadowing.MAJOR, "Marceline frowning at the tapes; Ice King/Marceline's past"),
    (138, 158, Foreshadowing.MAJOR, "Finn's past life missing an arm; Finn losing his arm"),
    (138, 160, Foreshadowing.MAJOR, "PB gifting Finn's past life an arm; PB doing same for Finn"),
    (162, 175, Foreshadowing.MAJOR, "Finn-sword appearing in Finn's dream"),
    (195, 198, Foreshadowing.MAJOR, "The Catalyst Comet"),
    (258, 261, Foreshadowing.MAJOR, "LSP's immunity to the slime corruption; LSP being the anti-elemental"),
    (260, 261, Foreshadowing.MAJOR, "LSP's immunity to the candy corruption; LSP being the anti-elemental"),
]
