#! /usr/bin/env python3
# -*- coding: utf-8 -*-

from show_continuity import *

'''Continuity data on the show Amphibia.'''

show = Show(
    title='Amphibia',
    # Season colors / episode titles from https://en.wikipedia.org/wiki/Amphibia_(TV_series)#Episodes
    seasons={
        1: {'color': '#3CB371',
            'episodes': {
                'S1E1a': 'Anne or Beast?',
                'S1E1b': 'Best Fronds',
                'S1E2a': 'Cane Crazy',
                'S1E2b': 'Flood, Sweat and Tears',
                'S1E3a': 'Hop Luck',
                'S1E3b': 'Stakeout',
                'S1E4a': 'The Domino Effect',
                'S1E4b': 'Taking Charge',
                'S1E5a': 'Anne Theft Auto',
                'S1E5b': 'Breakout Star',
                'S1E6a': 'Sprig Vs. Hop Pop',
                'S1E6b': 'Girl Time',
                'S1E7a': 'Dating Season',
                'S1E7b': 'Anne Vs. Wild',
                'S1E8a': 'Contagi-Anne',
                'S1E8b': 'Family Shrub',
                'S1E9a': 'Lily Pad Thai',
                'S1E9b': 'Plantar’s Last Stand',
                'S1E10a': 'Toad Tax',
                'S1E10b': 'Prison Break',
                'S1E11a': 'Grubhog Day',
                'S1E11b': 'Hop Pop and Lock',
                'S1E12a': 'Civil Wart',
                'S1E12b': 'Hop-Popular',
                'S1E13a': 'Croak and Punishment',
                'S1E13b': 'Trip to the Archives',
                'S1E14a': 'Snow Day',
                'S1E14b': 'Cracking Mrs. Croaker',
                'S1E15a': 'A Night at The Inn',
                'S1E15b': 'Wally and Anne',
                'S1E16a': 'Family Fishing Trip',
                'S1E16b': 'Bizarre Bazaar',
                'S1E17a': 'Cursed!',
                'S1E17b': 'Fiddle Me This',
                'S1E18a': 'The Big Bugball Game',
                'S1E18b': 'Combat Camp',
                'S1E19a': 'Children of the Spore',
                'S1E19b': 'Anne of the Year',
                'S1E20': 'Reunion'}},
        2: {'color': '#5499FF',
            'episodes': {
                'S2E1a': 'Handy Anne',
                'S2E1b': 'Fort in the Road',
                'S2E2a': 'The Ballad of Hopediah Plantar',
                'S2E2b': 'Anne Hunter',
                'S2E3a': 'Truck Stop Polly',
                'S2E3b': 'A Caravan Named Desire',
                'S2E4a': "Quarreler's Pass",
                'S2E4b': 'Toadcatcher',
                'S2E5a': 'Swamp and Sensibility',
                'S2E5b': 'Wax Museum',
                'S2E6': 'Marcy at the Gates',
                'S2E7a': 'Scavenger Hunt',
                'S2E7b': 'The Plantars Check In',
                'S2E8a': 'Lost in Newtopia',
                'S2E8b': 'Sprig Gets Schooled',
                'S2E9a': 'Little Frogtown',
                'S2E9b': 'Hopping Mall',
                'S2E10a': 'The Sleepover to End All Sleepovers',
                'S2E10b': 'A Day at the Aquarium',
                'S2E11': 'The Shut-In!',
                'S2E12a': 'Night Drivers',
                'S2E12b': 'Return to Wartwood',
                'S2E13a': 'Ivy on the Run',
                'S2E13b': 'After the Rain',
                'S2E14': 'The First Temple',
                'S2E15a': 'New Wartwood',
                'S2E15b': 'Friend or Frobo?',
                'S2E16a': 'Toad to Redemption',
                'S2E16b': 'Maddie & Marcy',
                'S2E17a': 'The Second Temple',
                'S2E17b': "Barrel's Warhammer",
                'S2E18a': 'Bessie & MicroAngelo',
                'S2E18b': 'The Third Temple',
                'S2E19a': 'The Dinner',
                'S2E19b': 'Battle of the Bands',
                'S2E20': 'True Colors'}}})

show.plot_threads = [
    ('S1E1a', 'S1E1b', Plot.CAUSAL, "Anne trapped in Amphibia / Anne's homesickness"),
    ('S1E1a', 'S1E1b', Plot.CAUSAL, "Sasha trapped in Amphibia"),
    ('S1E1a', 'S1E7b', Plot.CAUSAL, 'Music box arc'),
    ('S1E1b', 'S1E10b', Plot.CAUSAL, 'Sasha arc'),
    ('S1E9b', 'S1E12b', Plot.CAUSAL, "Plantars losing their vegetable stand"),
    ('S1E1a', 'S1E13b', Plot.CAUSAL, "Plantars preparing for the trip to find Anne a way home"),
    ('S1E7b', 'S1E16b', Plot.CAUSAL, 'Music box arc'),
    ('S1E13b', 'S1E16b', Plot.REFERENTIAL, 'Failed trip to the archives'),
    ('S1E3a', 'S1E17a', Plot.CAUSAL, "Sprig's engagement to Maddie"),
    ('S1E7a', 'S1E19b', Plot.CAUSAL, "Sprig's crush on Ivy"),
    ('S1E10b', 'S1E19b', Plot.CAUSAL, 'Sasha arc'),
    ('S1E10a', 'S1E19b', Plot.CAUSAL, "Hop Pop having accidentally incited a rebellion against the toads"),
    # Not sure how to cover multiple factors being mentioned as contributors to an event; e.g. both the defiance of the
    # toad tax and Hop Pop's run for mayor. Counting them both as fully causal seems wrong so for now I'm only marking
    # the first factor as causal and the rest as referential
    ('S1E12b', 'S1E19b', Plot.REFERENTIAL, "Hop Pop having accidentally incited a rebellion against the toads"),
    ('S1E19b', 'S1E20', Plot.SERIAL, "Grime/Sasha's invasion"),
    ('S1E20', 'S2E1a', Plot.CAUSAL, "Plantars' plan to get Anne home"),
    ('S2E1a', 'S2E1b', Plot.CAUSAL, "Plantars' trip to Newtopia"),
    ('S2E1a', 'S2E2a', Plot.CAUSAL, "Plantars' trip to Newtopia"),
    ('S2E1a', 'S2E2b', Plot.CAUSAL, "Plantars' trip to Newtopia"),
    ('S2E1a', 'S2E3a', Plot.CAUSAL, "Plantars' trip to Newtopia"),
    ('S2E1a', 'S2E3b', Plot.CAUSAL, "Plantars' trip to Newtopia"),
    ('S2E1a', 'S2E4a', Plot.CAUSAL, "Plantars' trip to Newtopia"),
    ('S1E20', 'S2E4b', Plot.CAUSAL, "Sasha/Grime as fugitives / Sasha's turmoil over Anne"),
    ('S1E15b', 'S2E5a', Plot.REFERENTIAL, "Wally teaching Anne not to mind what others think"),
    ('S2E1a', 'S2E5a', Plot.CAUSAL, "Plantars' trip to Newtopia"),
    ('S2E1a', 'S2E5b', Plot.CAUSAL, "Plantars' trip to Newtopia"),
    ('S1E1a', 'S2E6', Plot.CAUSAL, "Marcy trapped in Amphibia"),
    ('S2E1a', 'S2E6', Plot.CAUSAL, "Plantars' trip to Newtopia"),
    ('S2E6', 'S2E7a', Plot.CAUSAL, "Plantars and Marcy in Newtopia"),
    ('S1E16b', 'S2E7b', Plot.CAUSAL, "Hop Pop hiding the music box"),
    ('S2E6', 'S2E7b', Plot.CAUSAL, "Plantars and Marcy in Newtopia"),
    ('S2E6', 'S2E8a', Plot.CAUSAL, "Plantars in Newtopia"),
    ('S2E7b', 'S2E8a', Plot.REFERENTIAL, "Andrias/Marcy researching the music box"),
    ('S2E6', 'S2E8b', Plot.CAUSAL, "Plantars in Newtopia"),
    ('S2E6', 'S2E9a', Plot.CAUSAL, "Plantars in Newtopia"),
    ('S2E6', 'S2E9b', Plot.CAUSAL, "Plantars in Newtopia"),
    ('S2E6', 'S2E10a', Plot.CAUSAL, "Plantars in Newtopia"),
    ('S2E7b', 'S2E10b', Plot.CAUSAL, "Andrias/Marcy researching the music box"),
    ('S2E1a', 'S2E12a', Plot.CAUSAL, "Plantars' trip to Newtopia"),
    ('S2E1a', 'S2E12b', Plot.CAUSAL, "Plantars' trip to Newtopia"),
    ('S1E5a', 'S2E12a', Plot.REFERENTIAL, "Bessy's manual"),
    ('S2E1a', 'S2E13a', Plot.REFERENTIAL, "Plantars' trip to Newtopia"),
    ('S1E16b', 'S2E13b', Plot.CAUSAL, "Hop Pop hiding the music box"),
    ('S2E10b', 'S2E13b', Plot.CAUSAL, "The plan to charge the music box"),
    ('S2E13b', 'S2E14', Plot.CAUSAL, "Anne having discovered Hop Pop's lie"),
    ('S2E10b', 'S2E14', Plot.CAUSAL, "The plan to charge the music box"),
    ('S2E14', 'S2E15a', Plot.CAUSAL, "Marcy in Wartwood after first temple"),
    ('S2E1b', 'S2E15b', Plot.CAUSAL, "Robot that followed the Plantars"),
    ('S1E20', 'S2E16a', Plot.CAUSAL, "The fall of Toad Tower"),
    ('S2E14', 'S2E16b', Plot.CAUSAL, "Marcy in Wartwood after first temple"),
    ('S2E10b', 'S2E17a', Plot.CAUSAL, "The plan to charge the music box"),
    ('S2E4b', 'S2E17b', Plot.CAUSAL, "Sasha/Grime's plan to take over Newtopia"),
    ('S2E9b', 'S2E18a', Plot.CAUSAL, "MicroAngelo"),
    ('S2E10b', 'S2E18b', Plot.CAUSAL, "The plan to charge the music box"),
    ('S1E20', 'S2E18b', Plot.CAUSAL, "Sasha/Anne's falling out"),
    ('S2E4b', 'S2E18b', Plot.CAUSAL, "Sasha/Grime's plan to take over Newtopia"),
    ('S1E20', 'S2E19a', Plot.CAUSAL, "Sasha/Anne's falling out"),
    ('S2E18b', 'S2E19a', Plot.CAUSAL, "Sasha/Grime joining the Plantars"),
    ('S2E18b', 'S2E19b', Plot.CAUSAL, "Sasha/Grime joining the Plantars"),
    ('S2E10b', 'S2E20', Plot.CAUSAL, "The plan to charge the music box"),
    ('S2E18b', 'S2E20', Plot.CAUSAL, "Sasha/Grime joining the Plantars / plan to take over Newtopia"),
    ('S2E17b', 'S2E20', Plot.CAUSAL, "The toad armies supporting Grime/Sasha"),
    ('S2E17a', 'S2E20', Plot.CAUSAL, "The improperly charged music box")]

show.foreshadowing = [
    ('S1E3b', 'S2E20', Foreshadowing.MAJOR, '''Blue-haired Anne in hallucination'''),
    #('S1E3b', 'S3E??', Foreshadowing.MAJOR, '''Red/blue magic beings (Sasha/Anne) teaming up to defeat green magic monster (Marcy)'''),
    ('S1E17a', 'S1E20', Foreshadowing.MAJOR, '''Rebellion mentioned in newspaper'''),
    ('S2E6', 'S2E20', Foreshadowing.MAJOR, '''"One of these days, she's gonna get herself killed."''', "Andrias stabbing Marcy")]
    #('S2E19b', 'S3E??', Foreshadowing.MAJOR, '''"I'm the personification of metamorphosis!"''', "Test tube Marcy"),
