#! /usr/bin/env python3
# -*- coding: utf-8 -*-

from show_continuity import *

'''Continuity data on the show Bojack Horseman.'''

show = Show(
    title='Bojack Horseman',
    brief_title='Bojack',
    seasons={1: dict(num_eps=12, color='#006600'),
             2: dict(num_eps=12, color='#005B9C'),
             3: dict(num_eps=12, color='#644D36'),
             4: dict(num_eps=12, color='#FAA009'),
             5: dict(num_eps=12, color='#FF5C77'),
             6: dict(num_eps=16, color='#301934')},
    episodes={
        1: 'BoJack Horseman: The BoJack Horseman Story, Chapter One',
        2: 'BoJack Hates the Troops',
        3: 'Prickly-Muffin',
        4: 'Zoës and Zeldas',
        5: 'Live Fast, Diane Nguyen',
        6: "Our A-Story is a 'D' Story",
        7: 'Say Anything',
        8: 'The Telescope',
        9: 'Horse Majeure',
        10: 'One Trick Pony',
        11: 'Downer Ending',
        12: 'Later',
        14: 'Brand New Couch',
        15: 'Yesterdayland',
        16: 'Still Broken',
        17: 'After the Party',
        18: 'Chickens',
        19: 'Higher Love',
        20: 'Hank After Dark',
        21: "Let's Find Out",
        22: 'The Shot',
        23: 'Yes And',
        24: 'Escape From L.A.',
        25: 'Out to Sea',
        26: 'Start Spreading The News',
        27: 'The BoJack Horseman Show',
        28: 'BoJack Kills',
        29: 'Fish Out of Water',
        30: 'Love And/Or Marriage',
        31: 'Brrap Brrap Pew Pew',
        32: 'Stop the Presses',
        33: 'Old Acquaintance',
        34: 'Best Thing That Ever Happened',
        35: "It's You",
        36: "That's Too Much, Man!",
        37: 'That Went Well',
        38: 'See Mr. Peanutbutter Run',
        39: 'The Old Sugarman Place',
        40: 'Hooray! Todd Episode!',
        41: 'Commence Fracking',
        42: 'Thoughts and Prayers',
        43: 'Stupid Piece of Sh*t',
        44: 'Underground',
        45: 'The Judge',
        46: 'Ruthie',
        47: 'lovin that cali lifestyle!!',
        48: "Time's Arrow",
        49: 'What Time Is It Right Now',
        50: 'The Light Bulb Scene',
        51: 'The Dog Days Are Over',
        52: 'Planned Obsolescence',
        53: 'BoJack the Feminist',
        54: 'The Amelia Earhart Story',
        55: 'Free Churro',
        56: 'INT. SUB',
        57: "Mr. Peanutbutter's Boos",
        58: 'Ancient History',
        59: 'Head in the Clouds',
        60: 'The Showstopper',
        61: 'The Stopped Show',
        62: 'A Horse Walks into a Rehab',
        63: 'The New Client',
        64: 'Feel-Good Story',
        65: 'Surprise!',
        66: 'A Little Uneven, Is All',
        67: 'The Kidney Stays in the Picture',
        68: 'The Face of Depression',
        69: "A Quick One, While He's Away",
        70: 'Intermediate Scene Study w/ BoJack Horseman',
        71: 'Good Damage',
        72: 'Sunk Cost and All That',
        73: 'Xerox of a Xerox',
        74: 'The Horny Unicorn',
        75: 'Angela',
        76: 'The View From Halfway Down',
        77: 'Nice While It Lasted'})

show.plot_threads = [
    (1, 2, Plot.CAUSAL, "Diane ghostwriting for Bojack"),
    (5, 6, Plot.CAUSAL, "Bojack and Diane's trip"),
    (3, 7, Plot.CAUSAL, "The paparazzi photos of Bojack and Sarah Lynn"),
    (5, 7, Plot.CAUSAL, "Bojack's call to Herb"),
    (7, 8, Plot.CAUSAL, "Herb's invitation to Bojack"),
    (4, 9, Plot.CAUSAL, "Bojack having sabotaged Todd's rock opera"),
    (8, 9, Plot.CAUSAL, "Bojack having kissed Diane"),
    (1, 10, Plot.CAUSAL, "Diane ghostwriting for Bojack"),
    (9, 10, Plot.CAUSAL, "Todd having found out about Bojack's sabotage of the rock opera"),
    (10, 11, Plot.CAUSAL, "The completed memoir"),
    (9, 12, Plot.CAUSAL, "P. Carolyn/Vincent's relationship"),
    (11, 12, Plot.CAUSAL, "The memoir's effect on Bojack's life"),
    (12, 14, Plot.CAUSAL, "The Secretariat movie"),
    (12, 14, Plot.REFERENTIAL, "Sebastian St. Clair's invitation to Diane"),
    (11, 15, Plot.CAUSAL, "Bojack's memoir having been published"),
    (12, 16, Plot.CAUSAL, "Sebastian St. Clair's invitation to Diane"),
    (9, 17, Plot.CAUSAL, "P. Carolyn/Vincent's relationship"),
    (15, 17, Plot.CAUSAL, "Bojack/Wanda's relationship"),
    (12, 18, Plot.CAUSAL, "The Secretariat movie"),
    (17, 18, Plot.REFERENTIAL, "Bojack's car being damaged after hitting the deer"),
    (12, 19, Plot.CAUSAL, "Todd/Mr. PB's business ventures"),
    (15, 19, Plot.CAUSAL, "Bojack/Wanda's relationship"),
    (11, 20, Plot.CAUSAL, "Bojack's memoir having been published"),
    (12, 20, Plot.CAUSAL, "Sebastian St. Clair's invitation to Diane"),
    (19, 20, Plot.CAUSAL, "Mr. PB/Wanda's new show"),
    (19, 20, Plot.CAUSAL, "Secretariat being put on hold due to Corduroy's death"),
    (8, 21, Plot.CAUSAL, "Bojack having kissed Diane"),
    (19, 21, Plot.CAUSAL, "Mr. PB/Wanda's new show"),
    (20, 21, Plot.CAUSAL, "Diane's trip to Cordovia"),
    (12, 22, Plot.CAUSAL, "The Secretariat movie"),
    (19, 22, Plot.CAUSAL, "Rutabaga's divorce"),
    (20, 22, Plot.CAUSAL, "Diane's trip to Cordovia"),
    (15, 23, Plot.CAUSAL, "Bojack/Wanda's relationship"),
    (16, 23, Plot.CAUSAL, "Bojack seeing Charlotte again"),
    (22, 23, Plot.CAUSAL, "Diane crashing at Bojack's place"),
    (22, 23, Plot.CAUSAL, "P. Carolyn and Rutabaga's new agency"),
    (22, 23, Plot.CAUSAL, "Kelsey having been fired"),
    (8, 24, Plot.REFERENTIAL, "Charlotte having referred to L.A. as a tar pit"),
    (23, 24, Plot.SERIAL, "Bojack visiting Charlotte"),
    (22, 25, Plot.CAUSAL, "P. Carolyn and Rutabaga's new agency"),
    (22, 25, Plot.CAUSAL, "Diane crashing at Bojack's place"),
    (23, 25, Plot.CAUSAL, "Todd and the improv group"),
    (24, 25, Plot.CAUSAL, "Secretariat having completed without Bojack while he was in New Mexico"),
    (12, 26, Plot.CAUSAL, "Todd/Mr. PB's business ventures (PB Livin)"),
    (24, 26, Plot.CAUSAL, "Bojack's moral turmoil over the incident with Penny"),
    (25, 26, Plot.CAUSAL, "Bojack promoting Secretariat"),
    (25, 26, Plot.CAUSAL, "P. Carolyn's new agency"),
    (25, 26, Plot.CAUSAL, "Diane's celebrity Tweets job"),
    (27, 1, Plot.CAUSAL, "Events leading to the various characters' present-day situations"),
    (25, 28, Plot.CAUSAL, "Bojack promoting Secretariat"),
    (25, 28, Plot.CAUSAL, "Diane's celebrity Tweets job"),
    (22, 29, Plot.CAUSAL, "Bojack's involvement in Kelsey getting fired"),
    (25, 29, Plot.CAUSAL, "Bojack promoting Secretariat"),
    (25, 30, Plot.CAUSAL, "Secretariat's release"),
    (27, 30, Plot.CAUSAL, "Todd/Emily's relationship"),
    (28, 30, Plot.CAUSAL, "Diane/Mr. PB's relationship being on the rocks"),
    (25, 31, Plot.CAUSAL, "Diane's celebrity Tweets job"),
    (30, 31, Plot.CAUSAL, "Diane's pregnancy"),
    (30, 32, Plot.CAUSAL, "Todd and Emily's almost-hookup"),
    (31, 32, Plot.CAUSAL, "Bojack/Ana's relationship"),
    (25, 33, Plot.CAUSAL, "P. Carolyn's new agency"),
    (32, 33, Plot.CAUSAL, "Cabracadabra / Todd/Bojack's fight about Emily"),
    (30, 33, Plot.CAUSAL, "Diane/Mr. PB's plan to visit his family"),
    (33, 34, Plot.CAUSAL, "Bojack/P. Carolyn failing to land any parts"),
    (25, 35, Plot.CAUSAL, "Secretariat's release"),
    (30, 35, Plot.CAUSAL, "P. Carolyn/Ralph's date"),
    (32, 35, Plot.CAUSAL, "Todd/Bojack's fight about Emily"),
    (33, 35, Plot.CAUSAL, "Captain PB's twisted spleen"),
    (33, 35, Plot.CAUSAL, "Judah having been told of a potential merger for P. Carloyn's agency"),
    (24, 36, Plot.CAUSAL, "Bojack/Penny incident"),
    (35, 36, Plot.CAUSAL, "Bojack's relationships falling apart and worsening depression"),
    (26, 37, Plot.CAUSAL, "Mr. PB having bought a large number of spaghetti strainers"),
    (32, 37, Plot.CAUSAL, "Todd/Emily's falling out"),
    (33, 37, Plot.CAUSAL, "Bojack working for Ethan Around"),
    (33, 37, Plot.CAUSAL, "Cabracadabra having hired orcas"),
    (34, 37, Plot.CAUSAL, "Sandro having quit Bojack's restaurant"),
    (35, 37, Plot.CAUSAL, "P. Carolyn/Ralph's relationship"),
    (35, 37, Plot.CAUSAL, "Diane having been laid off"),
    (36, 37, Plot.CAUSAL, "Sarah Lynn's death"),
    (35, 38, Plot.CAUSAL, "P. Carolyn/Ralph's relationship"),
    (37, 38, Plot.CAUSAL, "Mr. PB running for governor"),
    (37, 38, Plot.CAUSAL, "Todd realizing he's asexual"),
    (37, 39, Plot.SERIAL, "Bojack soul-searching in Michigan"),
    (38, 39, Plot.REFERENTIAL, "Diane's call to Bojack"),
    (37, 40, Plot.CAUSAL, "Hollyhock looking for Bojack"),
    (37, 40, Plot.CAUSAL, "MR. PB running for governor"),
    (37, 40, Plot.CAUSAL, "Diane working at Girl Croosh"),
    (37, 40, Plot.CAUSAL, "Todd's asexuality"),
    (37, 41, Plot.CAUSAL, "Diane working at Girl Croosh"),
    (38, 41, Plot.CAUSAL, "P. Carolyn and Ralph trying to have a baby"),
    (40, 41, Plot.SERIAL, "Hollyhock visiting Bojack"),
    (40, 41, Plot.CAUSAL, "Mr. PB's pro-fracking campaign"),
    (37, 41, Plot.CAUSAL, "Diane working at Girl Croosh"),
    (40, 42, Plot.REFERENTIAL, "Todd/Courtney Portnoy's fake engagement"),
    (41, 42, Plot.CAUSAL, "Hollyhock/Bojack's hunt for her mother"),
    (40, 43, Plot.CAUSAL, "Todd/Courtney Portnoy's fake engagement"),
    (40, 43, Plot.CAUSAL, "Todd going to the asexual meetups"),
    (41, 43, Plot.CAUSAL, "P. Carolyn and Ralph trying to have a baby"),
    (41, 43, Plot.CAUSAL, "Hollyhock living with Bojack"),
    (42, 43, Plot.CAUSAL, "Beatrice living with Bojack"),
    (42, 43, Plot.CAUSAL, "Courtney Portnoy's movie having been cancelled"),
    (38, 44, Plot.CAUSAL, "Mr. PB's campaign for governor"),
    (39, 44, Plot.CAUSAL, "Bojack not having told Diane about his return from Michigan"),
    (41, 44, Plot.CAUSAL, "The fracking drills around Mr. PB/Diane's house"),
    (43, 44, Plot.REFERENTIAL, "P. Carolyn's pregnancy"),
    (12, 45, Plot.CAUSAL, "Todd/Mr. PB's business ventures (PB Livin)"),
    (35, 45, Plot.CAUSAL, "P. Carolyn/Ralph's relationship"),
    (41, 45, Plot.CAUSAL, "Hollyhock living with Bojack"),
    (42, 45, Plot.REFERENTIAL, "Beatrice living with Bojack"),
    (43, 45, Plot.CAUSAL, "P. Carolyn's pregnancy"),
    (43, 45, Plot.CAUSAL, "Bojack's deal to appear on Felicity Huffman's show"),
    (44, 45, Plot.REFERENTIAL, "Diane's suggestion that Hollyhock submit a mutual consent adoption form"),
    (44, 45, Plot.CAUSAL, "Mr. PB's decision to drop out of the election"),
    (44, 45, Plot.REFERENTIAL, "Mr. PB/Diane's house having been destroyed"),
    (49, 45, Plot.REFERENTIAL, "Beatrice and Corbin Creamerman"),
    (35, 46, Plot.CAUSAL, "Judah not having told P. Carolyn about the merger offer"),
    (41, 46, Plot.CAUSAL, "Hollyhock/Bojack's hunt for her mother"),
    (42, 46, Plot.CAUSAL, "Courtney Portnoy's movie having been cancelled"),
    (43, 46, Plot.CAUSAL, "Courtney Portnoy's marriage falling through"),
    (43, 46, Plot.CAUSAL, "P. Carolyn's pregnancy"),
    (44, 46, Plot.REFERENTIAL, "P. Carolyn allowing Todd to stay at her old apartment"),
    (45, 46, Plot.REFERENTIAL, "Mr. PB helping Woodchuck's campaign"),
    (45, 46, Plot.REFERENTIAL, "Todd's clown dentists business"),
    (41, 47, Plot.CAUSAL, "Hollyhock living with Bojack"),
    (42, 47, Plot.CAUSAL, "Beatrice living with Bojack/Hollyhock and having secretly been drugging Hollyhock"),
    (44, 47, Plot.CAUSAL, "Woodchuck's having lost his hands and gotten transplants"),
    (45, 47, Plot.CAUSAL, "Mr. PB helping Woodchuck's campaign"),
    (45, 47, Plot.CAUSAL, "Todd's clown dentists business"),
    (46, 47, Plot.CAUSAL, "P. Carolyn's depression after the miscarriage and other breakdowns in her life"),
    (39, 48, Plot.CAUSAL, "Honey Sugarman's lobotomy"),
    (41, 48, Plot.CAUSAL, "Mystery of Hollyhock's mother"),
    (47, 48, Plot.SERIAL, "Bojack putting Beatrice in a retirement home"),
    (37, 49, Plot.REFERENTIAL, "Todd's asexuality"),
    (41, 49, Plot.CAUSAL, "Hollyhock/Bojack's hunt for her mother"),
    (44, 49, Plot.CAUSAL, "Mr. PB/Diane's house having been destroyed"),
    (45, 49, Plot.CAUSAL, "The letter to Beatrice"),
    (46, 49, Plot.CAUSAL, "P. Carolyn's decision to continue to try to have a child"),
    (47, 49, Plot.CAUSAL, "P. Carolyn helping create the show Philbert / forging Bojack's signature"),
    (47, 49, Plot.CAUSAL, "Hollyhock in the hopital"),
    (47, 49, Plot.CAUSAL, "Todd's clown dentists released in the woods"),
    (47, 49, Plot.REFERENTIAL, "Jessica's telling Diane about how Mr. PB used to show her magic eye posters"),
    (49, 50, Plot.CAUSAL, "Todd/Yolanda's relationship"),
    (49, 50, Plot.CAUSAL, "Bojack working on Philbert"),
    (49, 50, Plot.CAUSAL, "P. Carolyn deciding to adopt"),
    (49, 50, Plot.REFERENTIAL, "Bojack/Hollyhock finding out they're half-siblings"),
    (49, 50, Plot.CAUSAL, "Diane/Mr. PB marriage falling apart"),
    (50, 51, Plot.CAUSAL, "Diane/Mr. PB's divorce"),
    (49, 52, Plot.REFERENTIAL, "Bojack working on Philbert"),
    (49, 52, Plot.CAUSAL, "Todd/Yolanda's relationship"),
    (50, 52, Plot.CAUSAL, "Bojack/Gina's relationship"),
    (51, 52, Plot.CAUSAL, "Mr. PB/Pickles' relationship"),
    (37, 53, Plot.CAUSAL, "Diane working at Girl Croosh"),
    (49, 53, Plot.CAUSAL, "Bojack working on Philbert"),
    (24, 53, Plot.CAUSAL, "Bojack/Penny incident"),
    (49, 54, Plot.REFERENTIAL, "The Philbert movie"),
    (50, 54, Plot.CAUSAL, "P. Carolyn going to an adoption agency"),
    (50, 54, Plot.REFERENTIAL, "Todd working at WhatTimeIsItRightNow"),
    (53, 54, Plot.REFERENTIAL, "Diane and Mr. PB working on Philbert"),
    (5, 55, Plot.REFERENTIAL, "Diane's dad's funeral"),
    (44, 56, Plot.CAUSAL, "P. Carolyn allowing Todd to stay at her apartment"),
    (50, 56, Plot.CAUSAL, "Todd working at WhatTimeIsItRightNow"),
    (53, 56, Plot.CAUSAL, "Diane working on Philbert"),
    (53, 56, Plot.CAUSAL, "Diane having found out about the Bojack/Penny incident"),
    (50, 57, Plot.CAUSAL, "Diane/Mr. PB's divorce"),
    (51, 57, Plot.CAUSAL, "Mr. PB/Pickles' relationship"),
    (55, 57, Plot.REFERENTIAL, "Bojack's father having died in a duel"),
    (56, 57, Plot.CAUSAL, "Diane having obliquely written the Bojack/Penny incident into Philbert"),
    (57, 1, Plot.CAUSAL, "Todd staying with Bojack"),
    (46, 58, Plot.CAUSAL, "P.Carolyn/Ralph's failed relationship"),
    (49, 58, Plot.CAUSAL, "Bojack/Hollyhock having discovered they're half-siblings"),
    (50, 58, Plot.CAUSAL, "Todd's idea for an asexual dating app"),
    (50, 58, Plot.CAUSAL, "P. Carolyn going to an adoption agency"),
    (50, 58, Plot.CAUSAL, "Bojack/Gina's relationship"),
    (54, 58, Plot.CAUSAL, "Bojack's back injury"),
    (3, 59, Plot.REFERENTIAL, "The paparazzi photos of Bojack and Sarah Lynn"),
    (36, 59, Plot.REFERENTIAL, "Sarah Lynn's death"),
    (49, 59, Plot.CAUSAL, "Bojack working on Philbert"),
    (50, 59, Plot.CAUSAL, "Bojack/Gina's relationship"),
    (50, 59, Plot.CAUSAL, "Diane/Mr. PB's divorce"),
    (50, 59, Plot.CAUSAL, "Todd working at WhatTimeIsItRightNow"),
    (51, 59, Plot.CAUSAL, "Mr. PB/Pickles' relationship"),
    (53, 59, Plot.CAUSAL, "Diane and Mr. PB working on Philbert"),
    (53, 59, Plot.CAUSAL, "Diane having found out about the Bojack/Penny incident"),
    (58, 59, Plot.CAUSAL, "Bojack crashing his car to get more opioids"),
    (58, 59, Plot.CAUSAL, "Hendry Fondle"),
    (6, 60, Plot.REFERENTIAL, '''Bojack having stolen the Hollywood "D"'''),
    (24, 60, Plot.REFERENTIAL, "The Bojack/Penny incident"),
    (36, 60, Plot.REFERENTIAL, "Sarah Lynn's death"),
    (43, 60, Plot.REFERENTIAL, "Bojack having stolen Beatrice's doll"),
    (50, 60, Plot.CAUSAL, "Bojack/Gina's relationship"),
    (59, 60, Plot.CAUSAL, "Bojack OD'ing on painkillers"),
    (59, 60, Plot.CAUSAL, "Philbert having been renewed"),
    (59, 60, Plot.REFERENTIAL, "Mr PB. cheating on Pickles with Diane"),
    (37, 61, Plot.CAUSAL, "Diane working at Girl Croosh"),
    (54, 61, Plot.CAUSAL, "P. Carolyn trying to adopt Sadie's baby"),
    (59, 61, Plot.CAUSAL, "Mr PB. cheating on Pickles with Diane"),
    (59, 61, Plot.CAUSAL, "Hendry Fondle working at WhatTimeIsItRightNow"),
    (60, 61, Plot.CAUSAL, "The strangling incident"),
    (36, 62, Plot.CAUSAL, "Sarah Lynn's death"),
    (58, 62, Plot.REFERENTIAL, "Birthday Dad"),
    (61, 62, Plot.SERIAL, "Bojack in rehab"),
    (61, 62, Plot.REFERENTIAL, "Untitled Princess Carolyn Project"),
    (58, 63, Plot.CAUSAL, "Birthday Dad"),
    (59, 63, Plot.CAUSAL, "Mr PB. cheating on Pickles with Diane"),
    (61, 63, Plot.CAUSAL, "P. Carolyn having adopted Ruthie"),
    (61, 63, Plot.CAUSAL, "Bojack in rehab"),
    (37, 64, Plot.CAUSAL, "Diane working at Girl Croosh"),
    (61, 64, Plot.CAUSAL, "Bojack in rehab"),
    (44, 65, Plot.CAUSAL, "P. Carolyn allowing Todd to stay at her apartment"),
    (59, 65, Plot.CAUSAL, "Mr PB. cheating on Pickles with Diane"),
    (61, 65, Plot.CAUSAL, "Bojack in rehab"),
    (61, 65, Plot.CAUSAL, "Mr. PB having proposed to Pickles"),
    (61, 65, Plot.CAUSAL, "P. Carolyn having adopted Ruthie"),
    (64, 65, Plot.CAUSAL, "Diane deciding to move to Chicago"),
    (61, 66, Plot.CAUSAL, "Bojack in rehab"),
    (61, 66, Plot.REFERENTIAL, "Sharona's drinking"),
    (62, 66, Plot.REFERENTIAL, "The vodka-filled water bottle"),
    (63, 66, Plot.CAUSAL, "Birthday Dad TV show"),
    (64, 66, Plot.CAUSAL, "Diane moving to Chicago"),
    (65, 66, Plot.CAUSAL, "Word having gotten out of Mr. PB cheating"),
    (65, 66, Plot.CAUSAL, "Pickles/Mr. PB's plan to have her cheat to make things even"),
    (65, 66, Plot.CAUSAL, "Todd being Ruthie's nanny"),
    (64, 67, Plot.CAUSAL, "Diane moving to Chicago"),
    (65, 67, Plot.REFERENTIAL, "Todd being Ruthie's nanny"),
    (66, 67, Plot.CAUSAL, "The Hollywoo assistants going on strike"),
    (66, 67, Plot.CAUSAL, "Doctor Champ drunk / Bojack leaving rehab"),
    (66, 67, Plot.REFERENTIAL, "Diane writing a book"),
    (46, 68, Plot.CAUSAL, "P. Carolyn/Judah's falling out"),
    (49, 68, Plot.REFERENTIAL, "Bojack/Hollyhock finding out they're half-siblings"),
    (58, 68, Plot.CAUSAL, "The asexual dating app"),
    (61, 68, Plot.CAUSAL, "P. Carolyn having adopted Ruthie"),
    (65, 68, Plot.CAUSAL, "Pickles/Mr. PB's plan to have her cheat to make things even"),
    (66, 68, Plot.CAUSAL, "Bojack having framed Sharona in the past"),
    (66, 68, Plot.CAUSAL, "Diane's depression while trying to write her book"),
    (67, 68, Plot.CAUSAL, "Bojack attending AA meetings post-rehab"),
    (67, 68, Plot.CAUSAL, "Judah advocating for the Hollywoo assistants' strike"),
    (67, 68, Plot.CAUSAL, "Mr. PB as the face of depression"),
    (22, 69, Plot.CAUSAL, "Kelsey having been fired from her last show"),
    (24, 69, Plot.CAUSAL, "The Bojack/Penny incident"),
    (36, 69, Plot.CAUSAL, "Sarah Lynn's death"),
    (60, 69, Plot.CAUSAL, "The strangling incident"),
    (61, 70, Plot.CAUSAL, "Bojack's expenses from rehab"),
    (63, 70, Plot.REFERENTIAL, "Birthday Dad TV show"),
    (65, 70, Plot.CAUSAL, "Todd being Ruthie's nanny"),
    (67, 70, Plot.REFERENTIAL, "Bojack attending AA meetings post-rehab"),
    (68, 70, Plot.CAUSAL, "Bojack getting a job teaching at Wesleyan"),
    (68, 70, Plot.REFERENTIAL, "Todd/Maude's relationship"),
    (68, 70, Plot.CAUSAL, "Mr. PB's plan for Pickles to get even with him via Joey Pogo"),
    (69, 70, Plot.CAUSAL, "Hollyhock having heard of the Bojack/Penny incident"),
    (66, 71, Plot.CAUSAL, "Diane's depression while trying to write her book"),
    (69, 71, Plot.SERIAL, "The reporters' investigation into Sarah Lynn's death and the Bojack/Penny incident"),
    (71, 70, Plot.CAUSAL, "Charlotte's call to Bojack"),
    (70, 72, Plot.SERIAL, "Bojack's alarm at the investigation"),
    (70, 72, Plot.CAUSAL, "Bojack having sold Elefante to Mr. PB/Joey Pogo"),
    (70, 72, Plot.CAUSAL, "Mr. PB's plan for Pickles to get even with him via Joey Pogo"),
    (71, 72, Plot.SERIAL, "The reporters' investigation into Sarah Lynn's death and Bojack"),
    (64, 73, Plot.CAUSAL, "Diane having moved to Chicago"),
    (66, 73, Plot.CAUSAL, "The incident with Sarah Lynn drinking Bojack's vodka on-set"),
    (67, 73, Plot.CAUSAL, "Doctor Champ having gotten drunk"),
    (68, 73, Plot.CAUSAL, "Todd/Maude's relationship"),
    (66, 73, Plot.REFERENTIAL, "Diane's book"),
    (72, 73, Plot.CAUSAL, "The Bojack/Sarah Lynn story breaking"),
    (72, 73, Plot.CAUSAL, "Pickles leaving Mr. PB"),
    (63, 74, Plot.REFERENTIAL, "Birthday Dad TV show"),
    (67, 74, Plot.CAUSAL, "Bojack attending AA meetings post-rehab"),
    (71, 74, Plot.CAUSAL, "The new direction of Diane's book"),
    (72, 74, Plot.CAUSAL, "Pickles leaving Mr. PB"),
    (73, 74, Plot.CAUSAL, "The release of the damning interview with Bojack"),
    (73, 74, Plot.CAUSAL, "Todd/Maude moving in together"),
    (8, 75, Plot.CAUSAL, "Bojack's betrayal of Herb"),
    (50, 75, Plot.CAUSAL, "Diane/Mr. PB's past marriage"),
    (67, 75, Plot.CAUSAL, "Todd having donated a kidney to his mother"),
    (68, 75, Plot.CAUSAL, "P. Carolyn/Judah working together again"),
    (71, 75, Plot.CAUSAL, "Diane's novel"),
    (73, 75, Plot.CAUSAL, "The release of the damning interview with Bojack"),
    (74, 75, Plot.CAUSAL, "Bojack/Vance and The Horny Unicorn movie"),
    (74, 75, Plot.REFERENTIAL, "Bojack's home having been sold"),
    (16, 76, Plot.REFERENTIAL, "Herb's death"),
    (19, 76, Plot.REFERENTIAL, "Corduroy's death"),
    (36, 76, Plot.REFERENTIAL, "Sarah Lynn's death"),
    (55, 75, Plot.REFERENTIAL, "Beatrice's death"),
    (75, 76, Plot.SERIAL, "Bojack intoxicated in his old home"),
    (74, 77, Plot.CAUSAL, "Bojack's home having been sold"),
    (75, 77, Plot.CAUSAL, "P. Carolyn/Judah's relationship"),
    (76, 77, Plot.SERIAL, "Bojack's near-drowning / call to Diane")]

show.foreshadowing = [
    (1, 76, Foreshadowing.MAJOR, "Bojack falling into pool in the intro(s); Bojack's near-drowning"),
    (3, 36, Foreshadowing.MAJOR, '''"until I die tragically young"; Sarah Lynn's death'''),
    (11, 76, Foreshadowing.MAJOR, r'''"I'm too weak, too tired, so I just let the water take me under." "Yeesh, downer ending!"; Bojack's near-drowning'''),
    (35, 76, Foreshadowing.MAJOR, r'''"you're gonna go home, and you're gonna be so miserable you'll wanna kill yourself. And you're gonna have nobody left to stop you."; Bojack's near-drowning'''),
    (45, 47, Foreshadowing.MAJOR, r'''"I've been getting really fidgety [...] like I got tiny little bumps crawling around on the inside of my skin"; Beatrice drugging Hollyhock's coffee'''),
    (45, 47, Foreshadowing.MAJOR, r'''"wanna have breakfast first?" "I'm good with this coffee"; appetite suppression; Beatrice drugging Hollyhock's coffee"'''),
    (45, 47, Foreshadowing.MAJOR, r'''Hollyhock changing channels really fast and sorting all the house's loose change; Hyperactivity/hyperfocus; Beatrice drugging Hollyhock's coffee'''),
    (46, 47, Foreshadowing.MAJOR, r'''Hollyhock counting her teeth; Hyperfocus; Beatrice drugging Hollyhock's coffee"'''),
    (60, 68, Foreshadowing.MAJOR, '''Sharona appearing in a list of Bojack's regrets; The Sharona incident''')]