#! /usr/bin/env python3
# -*- coding: utf-8 -*-

from show_continuity import *

'''Continuity data on the show Bojack Horseman.'''

show = Show(
    title='Bojack Horseman',
    brief_title='Bojack',
    seasons={1: dict(num_eps=12, color='#006600'),
             'Special': dict(num_eps=1, color='#CCCCCC'),
             2: dict(num_eps=12, color='#005B9C'),
             3: dict(num_eps=12, color='#644D36'),
             4: dict(num_eps=12, color='#FAA009'),
             5: dict(num_eps=12, color='#FF5C77'),
             6: dict(num_eps=12, color='#301934')},
    episodes={
        1: 'BoJack Horseman: The BoJack Horseman Story, Chapter One',
        2: 'BoJack Hates the Troops',
        3: 'Prickly-Muffin',
        4: 'Zoës and Zeldas',
        5: 'Live Fast, Diane Nguyen',
        6: "Our A-Story is a 'D' Story",
        7: 'Say Anything',
        8: 'The Telescope',
        9: 'Horse Majeure',
        10: 'One Trick Pony',
        11: 'Downer Ending',
        12: 'Later',
        13: "Sabrina's Christmas Wish",
        14: 'Brand New Couch',
        15: 'Yesterdayland',
        16: 'Still Broken',
        17: 'After the Party',
        18: 'Chickens',
        19: 'Higher Love',
        20: 'Hank After Dark',
        21: "Let's Find Out",
        22: 'The Shot',
        23: 'Yes And',
        24: 'Escape From L.A.',
        25: 'Out to Sea',
        26: 'Start Spreading The News',
        27: 'The BoJack Horseman Show',
        28: 'BoJack Kills',
        29: 'Fish Out of Water',
        30: 'Love And/Or Marriage',
        31: 'Brrap Brrap Pew Pew',
        32: 'Stop the Presses',
        33: 'Old Acquaintance',
        34: 'Best Thing That Ever Happened',
        35: "It's You",
        36: "That's Too Much, Man!",
        37: 'That Went Well',
        38: 'See Mr. Peanutbutter Run',
        39: 'The Old Sugarman Place',
        40: 'Hooray! Todd Episode!',
        41: 'Commence Fracking',
        42: 'Thoughts and Prayers',
        43: 'Stupid Piece of Sh*t',
        44: 'Underground',
        45: 'The Judge',
        46: 'Ruthie',
        47: 'lovin that cali lifestyle!!',
        48: "Time's Arrow",
        49: 'What Time Is It Right Now',
        50: 'The Light Bulb Scene',
        51: 'The Dog Days Are Over',
        52: 'Planned Obsolescence',
        53: 'BoJack the Feminist',
        54: 'The Amelia Earhart Story',
        55: 'Free Churro',
        56: 'INT. SUB',
        57: "Mr. Peanutbutter's Boos",
        58: 'Ancient History',
        59: 'Head in the Clouds',
        60: 'The Showstopper',
        61: 'The Stopped Show',
        62: 'A Horse Walks into a Rehab',
        63: 'The New Client',
        64: 'Feel-Good Story',
        65: 'Surprise!',
        66: 'A Little Uneven, Is All',
        67: 'The Kidney Stays in the Picture',
        68: 'The Face of Depression',
        69: "A Quick One, While He's Away",
        70: 'Intermediate Scene Study w/ BoJack Horseman',
        71: 'Good Damage',
        72: 'Sunk Cost and All That',
        73: 'Xerox of a Xerox',
        74: 'The Horny Unicorn',
        75: 'Angela',
        76: 'The View From Halfway Down',
        77: 'Nice While It Lasted'})

show.plot_threads = [
    (1, 2, Plot.CAUSAL, "Bojack and Diane's ghostwriting"),
    #(3, ?, Plot.CAUSAL, "Sarah Lynn arc"),
    #(4, ?, Plot.CAUSAL, "Decapithon receipt")
]

show.foreshadowing = [
    (1, 76, Foreshadowing.MAJOR, "Bojack falling into pool in the intro(s)"),
    (3, 36, Foreshadowing.MAJOR, '''"until I die tragically young"; Sarah Lynn's death'''),
    (11, 76, Foreshadowing.MAJOR, r'''"I'm too weak, too tired, so I just let the water take me under." "Yeesh, downer ending!"''')]