#! /usr/bin/env python3
# -*- coding: utf-8 -*-

from show_continuity import *

'''Data on the show Gravity Falls.'''

show = Show(
    title='Gravity Falls',
    # Season colors also set to match Wikipedia
    # (Section colors from https://en.wikipedia.org/wiki/List_of_Gravity_Falls_episodes)
    seasons={
        1: {'color': '#19D39B',
            'episodes': {
                'S1E1': 'Tourist Trapped',
                'S1E2': 'The Legend of the Gobblewonker',
                'S1E3': 'Headhunters',
                'S1E4': 'The Hand That Rocks the Mabel',
                'S1E5': 'The Inconveniencing',
                'S1E6': 'Dipper vs. Manliness',
                'S1E7': 'Double Dipper',
                'S1E8': 'Irrational Treasure',
                'S1E9': "The Time Traveler's Pig",
                'S1E10': 'Fight Fighters',
                'S1E11': 'Little Dipper',
                'S1E12': 'Summerween',
                'S1E13': 'Boss Mabel',
                'S1E14': 'Bottomless Pit!',
                'S1E15': 'The Deep End',
                'S1E16': 'Carpet Diem',
                'S1E17': 'Boyz Crazy',
                'S1E18': 'Land Before Swine',
                'S1E19': 'Dreamscaperers',
                'S1E20': 'Gideon Rises'}},
        2: {'color': '#49C9FF',
            'episodes': {
                'S2E1': 'Scary-oke',
                'S2E2': 'Into the Bunker',
                'S2E3': 'The Golf War',
                'S2E4': 'Sock Opera',
                'S2E5': 'Soos and the Real Girl',
                'S2E6': 'Little Gift Shop of Horrors',
                'S2E7': 'Society of the Blind Eye',
                'S2E8': "Blendin's Game",
                'S2E9': 'The Love God',
                'S2E10': 'Northwest Mansion Mystery/Noir',
                'S2E11': 'Not What He Seems',
                'S2E12': 'A Tale of Two Stans',
                'S2E13': 'Dungeons, Dungeons & More Dungeons',
                'S2E14': 'The Stanchurian Candidate',
                'S2E15': 'The Last Mabelcorn',
                'S2E16': 'Roadside Attraction',
                'S2E17': 'Dipper and Mabel vs. the Future',
                'S2E18': 'Weirdmageddon Part 1',
                'S2E19': 'Weirdmageddon 2: Escape from Reality',
                'S2E20': 'Weirdmageddon 3: Take Back The Falls'}}})

show.plot_threads = [
    ('S1E1', 'S1E4', Plot.CAUSAL, 'Mystery of the Journals arc'),
    ('S1E4', 'S1E11', Plot.CAUSAL, 'Gideon arc'),
    ('S1E11', 'S1E19', Plot.CAUSAL, 'Gideon arc'),
    ('S1E1', 'S1E20', Plot.CAUSAL, 'Mystery of Stan and the vending machine door'),
    ('S1E19', 'S1E20', Plot.SERIAL, 'Gideon arc'),
    ('S2E2', 'S2E4', Plot.CAUSAL, 'The bunker laptop'),
    ('S1E9', 'S2E8', Plot.CAUSAL, "Blendin's revenge"),
    ('S2E3', 'S2E10', Plot.CAUSAL, "Pacifica/Pines' improved relationship"),
    ('S1E20', 'S2E11', Plot.CAUSAL, 'Portal machine arc'),
    ('S2E11', 'S2E12', Plot.CAUSAL, "The Stans' story"),
    ('S2E11', 'S2E13', Plot.CAUSAL, "Ford having been rescued"),
    ('S2E7', 'S2E20', Plot.CAUSAL, 'The memory erasing gun'),
    ('S2E11', 'S2E15', Plot.CAUSAL, 'The dimensional rift'),
    ('S2E15', 'S2E17', Plot.CAUSAL, 'The dimensional rift'),
    ('S2E17', 'S2E18', Plot.SERIAL, 'Weirdmageddon arc'),
    ('S2E18', 'S2E19', Plot.SERIAL, 'Weirdmageddon arc'),
    ('S2E19', 'S2E20', Plot.SERIAL, 'Weirdmageddon arc')]

show.foreshadowing = [
    ('S1E1', 'S1E9', Foreshadowing.MINOR, 'Blendin appears briefly in background'),
    ('S1E1', 'S1E19', Foreshadowing.MAJOR, "Bill references throughout Shack", "Bill's existence"),
    ('S1E1', 'S2E15', Foreshadowing.MAJOR, "Bill references throughout M. Shack", "Ford's involvement with Bill"),
    ('S1E1', 'S2E11', Foreshadowing.MAJOR, 'Intro theme cryptogram: "STAN IS NOT WHAT HE SEEMS"', 'The two Stans'),
    ('S1E1', 'S2E11', Foreshadowing.MAJOR, 'Shack totem pole depicts Kolus (imitator brother of Thunderbird)', 'The two Stans'),
    ('S1E1', 'S2E20', Foreshadowing.MAJOR, 'Zodiac wheel on intro cipher page'),
    ('S1E2', 'S1E4', Foreshadowing.MINOR, 'Gideon in ad on back of magazine'),
    ('S1E2', 'S1E8', Foreshadowing.MINOR, '"You call that Ben Franklin? He looks like a woman!"'),
    ('S1E2', 'S1E9', Foreshadowing.MINOR, 'Blendin appears briefly in background'),
    ('S1E2', 'S2E11', Foreshadowing.MAJOR, "STNLYMBL ('Stanley-mobile') license plate instead of 'Stanford-mobile'", 'The two Stans'),
    ('S1E3', 'S1E9', Foreshadowing.MINOR, 'Blendin appears briefly in background'),
    ('S1E3', 'S2E11', Foreshadowing.MAJOR, "Stan's strong reactions to the wax figure of himself", 'The two Stans'),
    ('S1E5', 'S1E20', Foreshadowing.MAJOR, 'Hallucinated dog seems to say "must distrust Grunkle" backwards', "Stan's portal machine"),
    ('S1E6', 'S1E15', Foreshadowing.MINOR, "Mer-people's existence mentioned"),
    ('S1E8', 'S1E9', Foreshadowing.MINOR, 'Time Baby mentioned in secret document'),
    ('S1E8', 'S2E7', Foreshadowing.MINOR, "Serial number on -$12 bill deciphers to 'BLIND'", 'Society of the Blind Eye'),
    ('S1E9', 'S1E10', Foreshadowing.MINOR, "Arcade shows briefly in 'camouflage' setting of Blendin's suit"),
    ('S1E9', 'S1E18', Foreshadowing.MINOR, "Sap-dinosaurs show briefly in 'camouflage' setting of Blendin's suit"),
    ('S1E9', 'S2E11', Foreshadowing.MAJOR, 'Ford in past Mystery Shack', 'The two Stans'),
    ('S1E11', 'S1E20', Foreshadowing.MAJOR, '"[The M. Shack] holds a secret you couldn\'t possibly imagine."', 'Journal 1 hidden in M. Shack'),
    ('S1E14', 'S2E12', Foreshadowing.MAJOR, '"I regularly commit massive tax fraud."', "Stan assuming Ford's identity"),
    ('S1E16', 'S2E11', Foreshadowing.MAJOR, "Spare room, glasses/Stan's reaction to them', 'The two Stans"),
    ('S1E17', 'S2E17', Foreshadowing.MAJOR, '"the apocalypse is coming soon"', 'Weirdmageddon'),
    ('S1E19', 'S2E11', Foreshadowing.MAJOR, "Pair of swings in Stan's memory, one broken", 'The two Stans'),
    ('S1E19', 'S2E11', Foreshadowing.MAJOR, 'Ford in background of wrestling memory', 'The two Stans'),
    ('S1E20', 'S2E7', Foreshadowing.MINOR, 'Cryptogram: SEARCH FOR THE BLINDEYE'),
    ('S1E20', 'S2E12', Foreshadowing.MAJOR, 'Rainbow prism reflection in Author flashback', 'Author lived in M. Shack'),
    ('S2E2', 'S2E10', Foreshadowing.MINOR, 'Threatened "last form you\'ll ever take" matches Dipper\'s pose when turned to wood'),
    ('S2E2', 'S2E11', Foreshadowing.MAJOR, '"That six-fingered nerd hasn\'t been the same in 30 years"', 'The two Stans'),
    ('S2E4', 'S2E11', Foreshadowing.MAJOR, '"who would sacrifice everything they\'d worked for just for their dumb sibling?"', 'The two Stans'),
    ('S2E12', 'S2E15', Foreshadowing.MAJOR, "Ford checking Stan's eyes", "Ford's involvement with Bill"),
    ('S2E15', 'S2E20', Foreshadowing.MAJOR, "Dipper tries to memory erase Ford when he thinks he's possessed", "Bill defeated via the memory eraser")]
