#! /usr/bin/env python3
# -*- coding: utf-8 -*-

from show_continuity import *

'''Continuity data on the show Odd Taxi.'''

show = Show(
    title='Odd Taxi',
    # Season colors / episode titles from https://en.wikipedia.org/wiki/Odd_Taxi#Episode_list
    seasons={
        1: {'color': '#CCCCFF',
            'episodes': {
                'E1': "The Eccentric Driver",
                'E2': "How To Spend a Long Night",
                'E3': "Borrowed Plumes and the Bodyguard",
                'E4': "Tanaka's Revolution",
                'E5': "Don't Call Me an Idol",
                'E6': 'Let Me Hear You Say, "What the Hell?"',
                'E7': "Trick or Treat",
                'E8': "Bless you",
                'E9': "The Hero's Melancholy",
                'E10': "We Have No Tomorrow",
                'E11': "If We Could Go Back to That Day",
                'E12': "Not Enough",
                'E13': "Where To?"}}})

show.plot_threads = [
    ('E1', 'E2', Plot.CAUSAL, "Dobu appearing in Kabasawa's selfie."),
    ('E5', 'E1', Plot.CAUSAL, "Dobu's connection with Shirakawa / having given her the eraser"),
    ('E1', 'E12', Plot.CAUSAL, "Shirakawa giving Odokawa the Donraku eraser"),
    ('E7', 'E1', Plot.CAUSAL, "Big Daimon's loyalty to Kuroda/Dobu as a result of the foundation's support"),
    ('E11', 'E1', Plot.CAUSAL, "Odokawa having given the missing girl a taxi ride"),
    ('E1', 'E2', Plot.CAUSAL, "Kakihana lying about his income in the dating app"),
    ('E1', 'E3', Plot.CAUSAL, "Big Daimon confiscating Odokawa's camera data and giving it to Dobu"),
    ('E6', 'E1', Plot.CAUSAL, "Dobu asking Shirakawa to get close to Odokawa"),
    ('E1', 'E2', Plot.SERIAL, "Shirakawa's taxi ride with Odokawa"),
    ('E13', 'E1', Plot.REFERENTIAL, "Odokawa's foundation graduation keychain"),
    ('E11', 'E2', Plot.CAUSAL, "Odokawa having given the missing girl a taxi ride"),
    ('E2', 'E3', Plot.REFERENTIAL, "Baba's new gig"),
    ('E3', 'E2', Plot.CAUSAL, "Kuroda ordering Dobu to investigate the missing girl"),
    ('E2', 'E3', Plot.SERIAL, "Dobu holding up Odokawa at gunpoint"),
    ('E2', 'E3', Plot.CAUSAL, "Shiho matching with Kakihana"),
    ('E1', 'E3', Plot.CAUSAL, "Goriki learning of the drugs missing during Shirakawa's shift"),
    ('E3', 'E4', Plot.CAUSAL, "Odokawa causing Tanaka to lose the dodo"),
    ('E3', 'E4', Plot.REFERENTIAL, "Dobu's buried gun"),
    ('E4', 'E5', Plot.CAUSAL, "Tanaka vowing revenge on Odokawa"),
    ('E2', 'E5', Plot.CAUSAL, "Yamamoto being instructed to retrieve the dash cam data"),
    ('E3', 'E5', Plot.CAUSAL, "Dobu asking Odokawa to report anyone asking about the dash cam data"),
    ('E1', 'E5', Plot.CAUSAL, "Goriki learning of the drugs missing during Shirakawa's shift"),
    ('E1', 'E5', Plot.CAUSAL, "Odokawa seeing Shirakawa meet Dobu"),
    ('E2', 'E5', Plot.CAUSAL, "Shiho matching with Kakihana"),
    ('E2', 'E5', Plot.REFERENTIAL, "Odokawa helping Imai pick lottery numbers"),
    ('E2', 'E5', Plot.CAUSAL, "Kabasawa becoming obsessed with Dobu"),
    ('E5', 'E6', Plot.REFERENTIAL, "The Mystery Kiss poster Yamamoto left in the taxi"),
    ('E2', 'E6', Plot.CAUSAL, "Odokawa helping Imai pick lottery numbers"),
    ('E5', 'E6', Plot.CAUSAL, "Tanaka hunting Odokawa via the planted phone"),
    ('E5', 'E6', Plot.CAUSAL, "Shiho telling Kakihana she wants an engagement ring"),
    ('E5', 'E6', Plot.CAUSAL, "Odokawa learning of Shirakawa's relation to Dobu"),
    ('E5', 'E6', Plot.CAUSAL, "Kakihana faking being rich"),
    ('E2', 'E6', Plot.CAUSAL, "Baba's new gig / Shibagaki and Baba drifting apart"),
    ('E5', 'E6', Plot.CAUSAL, "Kabasawa promising to capture Dobu"),
    ('E5', 'E6', Plot.CAUSAL, "Yamamoto asking Odokawa for the dashcam data"),
    ('E6', 'E7', Plot.CAUSAL, "Odokawa/Dobu working together / plan to deal with Tanaka and Kabasawa"),
    ('E5', 'E7', Plot.CAUSAL, "Tanaka hunting Odokawa via the planted phone"),
    ('E5', 'E7', Plot.CAUSAL, "Kakihana faking being rich"),
    ('E1', 'E7', Plot.REFERENTIAL, "The rumors of Odokawa having the missing girl in his apartment"),
    ('E1', 'E7', Plot.CAUSAL, "Big Daimon working for Dobu"),
    ('E6', 'E7', Plot.CAUSAL, "Odokawa learning of Dobu's plan to rob a bank"),
    ('E1', 'E7', Plot.CAUSAL, "The missing girl / the body bag"),
    ('E6', 'E7', Plot.CAUSAL, "Shirakawa's debt to Dobu removed"),
    ('E7', 'E8', Plot.SERIAL, "Kakihana kidnapped"),
    ('E7', 'E8', Plot.CAUSAL, "Ichimura wanting to stop running badger games"),
    ('E5', 'E8', Plot.CAUSAL, "Yamamoto asking Odokawa for the dashcam data"),
    ('E6', 'E8', Plot.CAUSAL, "Imai winning the lottery"),
    ('E7', 'E8', Plot.CAUSAL, "Goriki/Shirakawa investigating Odokawa's past"),
    ('E1', 'E7', Plot.CAUSAL, "Odokawa talking to someone in his apartment"),
    ('E7', 'E8', Plot.CAUSAL, "Kabasawa's video of Dobu on Halloween"),
    ('E7', 'E8', Plot.CAUSAL, "Odokawa promising to get more evidence on Dobu"),
    ('E3', 'E8', Plot.CAUSAL, "Kakihana showing Odokawa Ichimura's picture"),
    ('E8', 'E9', Plot.SERIAL, "Odokawa having connected Ichimura to Kakihana's disappearance"),
    ('E6', 'E9', Plot.CAUSAL, "Odokawa/Dobu working together"),
    ('E5', 'E9', Plot.CAUSAL, "Tanaka hunting Odokawa via the planted phone/GPS"),
    ('E5', 'E9', Plot.CAUSAL, "Kabasawa promising to capture Dobu"),
    ('E8', 'E9', Plot.CAUSAL, "Odokawa and Little Daimon's partnership"),  # Little Daimon having shot Dobu
    ('E6', 'E9', Plot.CAUSAL, "The ring Kakihana bought"),
    ('E7', 'E9', Plot.CAUSAL, "Goriki investigating Odokawa's past"),
    ('E6', 'E10', Plot.CAUSAL, "Satoshi pursuing Shibagaki"),
    ('E8', 'E10', Plot.CAUSAL, "Odokawa's negotiations with Yamamoto for the dashcam data"),
    ('E6', 'E10', Plot.CAUSAL, "Odokawa/Shirakawa's falling out"),
    ('E8', 'E10', Plot.CAUSAL, "Dobu and Yano's plans to rob Imai"),
    ('E8', 'E10', Plot.CAUSAL, "Odokawa having warned Imai of the plan to rob him"),
    ('E9', 'E10', Plot.CAUSAL, "Gouriki learning that Odokawa's parents were dead"),
    ('E7', 'E10', Plot.CAUSAL, "The missing girl's body being found"),
    ('E11', 'E6', Plot.CAUSAL, "Rui/Baba starting dating"),
    ('E11', 'E7', Plot.CAUSAL, "The dumped body"),
    ('E11', 'E2', Plot.CAUSAL, "The murder coverup / Yamamoto searching for the taxi"),
    ('E11', 'E2', Plot.CAUSAL, "Mystery Kiss having to work for the yakuza"),
    ('E10', 'E11', Plot.CAUSAL, "The missing girl's body being identified as Mitsuya"),
    ('E10', 'E11', Plot.CAUSAL, "Dobu's plan to steal from Yano"),
    ('E10', 'E11', Plot.CAUSAL, "Odokawa's instructions to Yamamoto for ruining Dobu's plan"),
    ('E6', 'E11', Plot.CAUSAL, "Shibagaki and Baba drifting even further apart"),
    ('E9', 'E11', Plot.CAUSAL, "Gouriki learning that Odokawa's parents were dead"),
    ('E11', 'E12', Plot.CAUSAL, "The updated robbery plans from each side"),
    ('E10', 'E12', Plot.CAUSAL, "Odokawa having found Tanaka's GPS tracker"),
    ('E11', 'E12', Plot.REFERENTIAL, "Mitsuya's keychain"),
    ('E11', 'E12', Plot.CAUSAL, "Shibagaki and Baba breaking up their partnership"),
    ('E5', 'E12', Plot.CAUSAL, "Tanaka hunting Odokawa via the planted phone/GPS"),
    ('E1', 'E12', Plot.CAUSAL, "Shirakawa giving Odokawa the Donraku eraser"),
    ('E4', 'E12', Plot.CAUSAL, "Tanaka's history with Ditch-11/Dobu"),
    ('E8', 'E12', Plot.CAUSAL, "Odokawa and Little Daimon's partnership"),
    ('E12', 'E13', Plot.SERIAL, "Odokawa fleeing from Yano/Sekiguchi"),
    ('E11', 'E13', Plot.CAUSAL, "Gouriki having found Odokawa's old journal"),
    ('E12', 'E13', Plot.CAUSAL, "Shibagaki and Baba's fight"),
    ('E11', 'E13', Plot.CAUSAL, "Wadagaki looking for Odokawa"),
    ('E1', 'E13', Plot.REFERENTIAL, "Kabasawa wanting to go viral"),
    ('E3', 'E13', Plot.REFERENTIAL, "Tanaka's phone falling in a ditch"),
    ('E9', 'E13', Plot.REFERENTIAL, "Kakihana throwing the engagement ring into a river"),
    ('E2', 'E13', Plot.REFERENTIAL, "Wadagaki's love of fried chicken"),
    ('E2', 'E13', Plot.REFERENTIAL, "Ichimura's love of baths"),
    ('E11', 'E13', Plot.REFERENTIAL, "Mitsuya's body being thrown in the harbor"),
    ('E12', 'E13', Plot.CAUSAL, "Dobu having been shot"),
    ('E1', 'E13', Plot.CAUSAL, "The contents of Odokawa's closet")]

show.foreshadowing = [
    ('E1', 'E13', Foreshadowing.MAJOR, "Odokawa meeting a regular cat in the OP", "The cat in Odokawa's closet"),
    ('E1', 'E13', Foreshadowing.MAJOR, "Regular cat tail in Odokawa's closet in the OP", "The cat in Odokawa's closet"),
    ('E1', 'E13', Foreshadowing.MAJOR, "Odokawa's figure drawn ambiguously when falling in water in OP", "Odokawa's condition"),
    ('E1', 'E5', Foreshadowing.MAJOR, "Odokawa's dream of water", "Odokawa's fear of water"),
    ('E1', 'E11', Foreshadowing.MAJOR, "Odokawa's dream of water", "Odokawa's childhood accident"),
    ('E1', 'E13', Foreshadowing.MAJOR, '''"Homosapiens"; The comedy duo's name''', "Odokawa's condition"),
    ('E1', 'E13', Foreshadowing.MAJOR, "Human figure on street sign", "Odokawa's condition"),
    ('E1', 'E11', Foreshadowing.MAJOR, '"Safe driving" keychain', "Odokawa's childhood accident"),
    ('E1', 'E13', Foreshadowing.MAJOR, '"I guessed on the vision test, though."', "Odokawa's condition"),
    ('E1', 'E11', Foreshadowing.MAJOR, "Odakawa's flashback to his mother driving", "Odokawa's childhood accident"),
    ('E1', 'E13', Foreshadowing.MAJOR, "Figures in Odokawa's flashback looking roughly human", "Odokawa's condition"),
    ('E1', 'E10', Foreshadowing.MAJOR, "Backup dancer and missing girl both being black cats", "The murder coverup"),
    ('E1', 'E13', Foreshadowing.MAJOR, "No response from the closet to Odokawa's questions.", "The cat in Odokawa's closet"),
    ('E1', 'E12', Foreshadowing.MAJOR, "Shirakawa deflecting the question of the eraser's origin",
                                       "Dobu having given Shirakawa the eraser"),
    ('E1', 'E13', Foreshadowing.MAJOR, "Medical diagrams of human organs in clinic", "Odokawa's condition"),
    ('E1', 'E13', Foreshadowing.MAJOR, '"What do I look like to you?" "A gorilla."; slightly off character reactions',
                                       "Odokawa's condition"),
    ('E1', 'E13', Foreshadowing.MAJOR, '''"It's something more... fundamental."''', "Odokawa's condition"),
    ('E1', 'E13', Foreshadowing.MAJOR, '''"You're the only alpaca around here."; Shirakawa laughs''', "Odokawa's condition"),
    ('E2', 'E5', Foreshadowing.MAJOR, '''"I feel like I should have [relied on parents instead of a loan]"''',
                                      "Shirakawa's debt to Dobu"),
    ('E2', 'E12', Foreshadowing.MAJOR, "Kuroda present when Odokawa says he'd like to thank the foundation",
                                       "Kuroda being the head of the foundation for traffic accident orphans"),
    ('E2', 'E5', Foreshadowing.MAJOR, '"You never get in the bath, Odokawa"', "Odokawa's fear of water"),
    ('E2', 'E10', Foreshadowing.MAJOR, "Mystery Kiss backup dancers being required to wear masks", "The murder coverup"),
    ('E2', 'E10', Foreshadowing.MAJOR, '''"Mitsuya's dancing has gotten a little sloppy."''', "The murder coverup"),
    ('E2', 'E10', Foreshadowing.MAJOR, '''"Yamamoto receiving a call about the dash cam data."''', "The murder coverup"),
    ('E2', 'E10', Foreshadowing.MAJOR, "Mitsuya's eye color differing in the flashback", "The murder coverup"),
    ('E2', 'E13', Foreshadowing.MAJOR, "Zooden / regular animals existing", "Odokawa's condition"),
    ('E2', 'E6', Foreshadowing.MAJOR, '"Well my girlfriend has the opportunity [to become famous]"', "Baba dating Nikaidou"),
    ('E3', 'E11', Foreshadowing.MAJOR, '''"It's Don-chan's daughter"''', "Missing girl being Donraku's daughter"),
    ('E3', 'E7', Foreshadowing.MAJOR, "Daimons' hatred of taxi drivers / accident flashback", "The Daimons' past"),
    ('E3', 'E7', Foreshadowing.MAJOR, "Shiho framed ominously in shadows when meeting Kakihana", "Shiho running a badger game"),
    ('E3', 'E7', Foreshadowing.MAJOR, "Yamamoto/Sekiguchi watching Kakihana/Shiho's date", "Shiho running a badger game"),
    ('E4', 'E13', Foreshadowing.MAJOR, "Tanaka's mother being a rabbit rather than a puma", "Odokawa's condition"),
    ('E4', 'E12', Foreshadowing.MAJOR, "Ditch-11 - kanji for ditch having a pronunciation of 'dobu'.", "Dobu being ditch-11"),
    ('E4', 'E13', Foreshadowing.MAJOR, "'History' being depicted with a walking ape", "Odokawa's condition"),
    ('E5', 'E13', Foreshadowing.MAJOR, "Wadagaki planting the phone for Tanaka", "Wadagaki being the killer"),
    ('E5', 'E7', Foreshadowing.MAJOR, '''"Exchanging messages with old dudes is exhausting"''', "Shiho running a badger game"),
    ('E5', 'E11', Foreshadowing.MAJOR, '''"I don't like her. I liked things better before."''', "The murder coverup"),
    ('E5', 'E13', Foreshadowing.MAJOR, '"There are plenty of people who look like her from behind."', "Odokawa's condition"),
    ('E5', 'E11', Foreshadowing.MAJOR, "Odakawa's fear of water", "Odokawa's childhood accident"),
    ('E6', 'E13', Foreshadowing.MAJOR, '"If anything, I find it strange that you guys are so bad at [finding people in a crowd]."',
                                       "Odokawa's condition"),
    ('E6', 'E13', Foreshadowing.MAJOR, '''"I don't want a pet with a horse face."''', "Odokawa's condition"),
    ('E7', 'E13', Foreshadowing.MAJOR, '''"Now you can't escape." while patching small window hole''', "The cat in Odokawa's closet"),
    ('E7', 'E13', Foreshadowing.MAJOR, "Odokawa explaining the extent of his people-recognition ability to Dobu",
                                       "Odokawa's condition"),
    ('E8', 'E13', Foreshadowing.MAJOR, '"A calico cat. Where have I seen one before?" "What are you talking about?"',
                                       "Odokawa's condition"),
    ('E8', 'E13', Foreshadowing.MAJOR, "Goriki's various tests of Odokawa's perception", "Odokawa's condition"),
    ('E8', 'E11', Foreshadowing.MAJOR, '"It was on the news the other day."', "The murder coverup"),
    # They'd already established regular animals exist but I think this was the first time a regular animal matched
    # the species of a character, so I'm counting it
    ('E9', 'E13', Foreshadowing.MAJOR, "Regular cats existing", "The cat in Odokawa's closet"),
    ('E9', 'E13', Foreshadowing.MAJOR, 'White hand / "I thought you were an amateur"',
                                       "Little Daimon having been the one to shoot Dobu"),
    ('E9', 'E13', Foreshadowing.MAJOR, "The pet dog looking like its owner per the common phrase", "Odokawa's condition"),
    ('E10', 'E13', Foreshadowing.MAJOR, '''"[I'll] laugh out loud like a porcupine."''', "Odokawa's condition"),
    ('E11', 'E13', Foreshadowing.MAJOR, '''"A huge thuggish guy" (not "a polar bear")''', "Odokawa's condition"),
    ('E11', 'E13', Foreshadowing.MAJOR, "Wadagaki having failed the same audition", "Wadagaki being the killer"),
    ('E11', 'E12', Foreshadowing.MAJOR,
     '''"broadly speaking, we've been on the same side since the beginning." / glance at 'safe driving' keychain''',
     "Daimons having been assisted by the same foundation as Odokawa"),
    ('E12', 'E13', Foreshadowing.MAJOR, "Dobu's count of the gun's bullets being incorrect",
                                        "Little Daimon having been the one to shoot Dobu")]
