#! /usr/bin/env python3
# -*- coding: utf-8 -*-

from show_continuity import *

'''Continuity data on the show She-Ra and the Princesses of Power.'''

# Parsed from https://en.wikipedia.org/wiki/List_of_She-Ra:_Princess_of_Power_episodes
show = Show(title='She-Ra and the Princesses of Power',
            seasons={1: dict(start=1, end=13, color='#512129'),
                     2: dict(start=14, end=20, color='#000000'),
                     3: dict(start=21, end=26, color='#AC0017'),
                     4: dict(start=27, end=39, color='#0048BA')},
            episodes={
                    1: 'The Sword Part 1',
                    2: 'The Sword Part 2',
                    3: 'Razz',
                    4: 'Flowers for She-Ra',
                    5: 'The Sea Gate',
                    6: 'System Failure',
                    7: 'In the Shadows of Mystacor',
                    8: 'Princess Prom',
                    9: 'No Princess Left Behind',
                    10: 'The Beacon',
                    11: 'Promise',
                    12: 'Light Hope',
                    13: 'The Battle of Bright Moon',
                    14: 'The Frozen Forest',
                    15: 'Ties That Bind',
                    16: 'Signals',
                    17: 'Roll With It',
                    18: 'White Out',
                    19: 'Light Spinner',
                    20: 'Reunion',
                    21: 'The Price of Power',
                    22: 'Huntara',
                    23: 'Once Upon a Time in the Waste',
                    24: 'Moment of Truth',
                    25: 'Remember',
                    26: 'The Portal',
                    27: 'The Coronation',
                    28: 'The Valley of the Lost',
                    29: 'Flutterina',
                    30: 'Pulse',
                    31: 'Protocol',
                    32: 'Princess Scorpia',
                    33: 'Mer-Mysteries',
                    34: "Boys' Night Out",
                    35: 'Hero',
                    36: 'Fractures',
                    37: 'Beast Island',
                    38: 'Destiny Part 1',
                    39: 'Destiny Part 2'})

show.plot_threads = [
    (1, 2, Plot.SERIAL, r'''Adora alone'''),
    (2, 3, Plot.SERIAL, r'''Adora alone'''),
    (3, 4, Plot.CAUSAL, r'''Recruiting Perfuma'''),
    (3, 5, Plot.CAUSAL, r'''Recruiting Mermista'''),
    (3, 6, Plot.CAUSAL, r'''Recruiting Entrapta'''),
    (3, 8, Plot.CAUSAL, r'''Recruting Frosta'''),
    (8, 9, Plot.SERIAL, r'''Glimmer rescue mission'''),
    (9, 10, Plot.CAUSAL, r'''Glimmer's injury'''),
    (9, 10, Plot.SERIAL, r'''Entrapta in Fright Zone'''),
    (10, 11, Plot.CAUSAL, r'''Healing Glimmer'''),
    (10, 11, Plot.CAUSAL, r'''Finding First Ones' tech'''),
    (11, 12, Plot.SERIAL, r'''Adora/Light Hope'''),
    (11, 12, Plot.CAUSAL, r'''Stolen First Ones' tech'''),
    (12, 13, Plot.SERIAL, r'''Hacked planet'''),
    (10, 14, Plot.CAUSAL, r'''Entrapta and the Horde'''),
    (12, 15, Plot.CAUSAL, r'''Adora training with Light Hope'''),
    (14, 15, Plot.CAUSAL, r'''Entrapta rescue mission'''),
    (6, 18, Plot.CAUSAL, r'''Virus First Ones' tech'''),
    # Should White Out (Horde acquires some piece of FO tech) causally affect them finishing the portal machine?
    # The general question is if the story involves some project and a bunch of otherwise episodic episodes involve
    # working on it, are they really causal to the episode where the show decides they finished? I guess it depends on
    # whether if the episode were removed the story would still make sense. E.g. in White Out the Horde finds some
    # generic piece of tech. If the story simply jumped from them starting to tinker on it to them finishing the portal
    # machine it wouldn't be less coherent. One could imagine cases where completing the task/project without some
    # task being addressed would not make sense however, I just don't think that's the case here.
    (16, 18, Plot.CAUSAL, r'''Searching for tech for the portal machine'''),
    (7, 19, Plot.CAUSAL, r'''Shadow Weaver's past'''),
    (16, 20, Plot.CAUSAL, r'''Mysterious Signal'''),
    (19, 20, Plot.SERIAL, r'''Shadow Weaver's escape'''),
    (19, 21, Plot.SERIAL, r'''Shadow Weaver escaping and joining the rebellion'''),
    (20, 21, Plot.CAUSAL, r'''Catra's punishment'''),
    (20, 21, Plot.CAUSAL, r'''Mysterious signal'''),
    (16, 22, Plot.CAUSAL, r'''The portal machine'''),
    (21, 22, Plot.SERIAL, r'''Crimson Waste arc'''),
    (22, 23, Plot.SERIAL, r'''Crimson Waste arc'''),
    (21, 24, Plot.CAUSAL, r'''Shadow Weaver helping the rebellion'''),
    (22, 24, Plot.CAUSAL, r'''The portal machine'''),
    (23, 24, Plot.SERIAL, r'''Adora captured'''),
    (24, 25, Plot.SERIAL, r'''The portal'''),
    (25, 26, Plot.SERIAL, r'''The portal'''),
    (26, 27, Plot.CAUSAL, r'''Loss of Angela / Glimmer's coronation'''),
    (24, 27, Plot.CAUSAL, r'''Catra's lie about Entrapta'''),
    (26, 27, Plot.CAUSAL, r'''Hordak/Catra blame for portal catastrophe'''),
    (22, 28, Plot.CAUSAL, r'''Mara's ship'''),
    (27, 28, Plot.REFERENTIAL, r'''Glimmer as queen'''),
    (28, 29, Plot.CAUSAL, r'''Double Trouble spy arc'''),
    (24, 30, Plot.CAUSAL, r'''Shadow Weaver teaching Glimmer arc'''),
    (29, 30, Plot.CAUSAL, r'''Double Trouble spy arc'''),
    (12, 31, Plot.CAUSAL, r'''Adora training with Light Hope'''),
    (23, 31, Plot.CAUSAL, r'''Mystery of Mara's past'''),
    (24, 32, Plot.CAUSAL, r'''Scorpia's feelings about Entrapta's fate'''),
    (30, 32, Plot.CAUSAL, r'''Double Trouble spy arc'''),
    (32, 33, Plot.CAUSAL, r'''Double Trouble spy arc, Hordak's weapon'''),
    (32, 34, Plot.CAUSAL, r'''Scorpia leaving the Horde'''),
    (23, 35, Plot.CAUSAL, r'''Mystery of Mara's past'''),
    (32, 36, Plot.SERIAL, r'''Scorpia joining the Rebellion'''),
    (35, 36, Plot.SERIAL, r'''Heart of Etheria arc'''),
    (36, 37, Plot.SERIAL, r'''Entrapta rescue mission'''),
    (33, 38, Plot.CAUSAL, r'''Double Trouble switching sides'''),
    (36, 38, Plot.CAUSAL, r'''Scorpia joining the Rebellion'''),  # Referential? Scorpia helping the rebellion kind of enters the canon arguably
    (37, 38, Plot.SERIAL, r'''Entrapta rescue mission, Heart of Etheria arc'''),
    (24, 39, Plot.CAUSAL, r'''The portal signal; Horde Prime's arrival'''),  # Might technically not have mattered?
    (31, 39, Plot.CAUSAL, r'''Mara/Light Hope's relationship'''),
    (38, 39, Plot.SERIAL, r'''Heart of Etheria arc''')]
