#! /usr/bin/env python3
# -*- coding: utf-8 -*-

from show_continuity import *

'''Continuity data on the show Star vs. the Forces of Evil.'''

# Parsed from https://en.wikipedia.org/wiki/List_of_Star_vs._the_Forces_of_Evil_episodes
show = Show(title='Star vs. the Forces of Evil',
            brief_title='Star vs.',
            seasons={1: dict(num_eps=24, color='#93DDB8'),
                     2: dict(num_eps=41, color='#FDE79C'),
                     3: dict(num_eps=38, color='#FE4C4C'),
                     4: dict(num_eps=37, color='#6B4423')},
            episodes={
                '1a': 'Star Comes to Earth',
                '1b': 'Party with a Pony',
                '2a': 'Matchmaker',
                '2b': 'School Spirit',
                '3a': 'Monster Arm',
                '3b': 'The Other Exchange Student',
                '4a': 'Cheer Up, Star',
                '4b': 'Quest Buy',
                '5a': 'Diaz Family Vacation',
                '5b': "Brittney's Party",
                '6a': 'Mewberty',
                '6b': 'Pixtopia',
                '7a': 'Lobster Claws',
                '7b': 'Sleep Spells',
                '8a': 'Blood Moon Ball',
                '8b': 'Fortune Cookies',
                '9a': 'Freeze Day',
                '9b': 'Royal Pain',
                10: "St. Olga's Reform School for Wayward Princesses",
                '11a': 'Mewnipendance Day',
                '11b': 'The Banagic Incident',
                '12a': 'Interdimensional Field Trip',
                '12b': 'Marco Grows a Beard',
                13: 'Storm the Castle',
                '14a': 'My New Wand!',
                '14b': 'Ludo in the Wild',
                '15a': 'Mr. Candle Cares',
                '15b': 'Red Belt',
                '16a': 'Star on Wheels',
                '16b': 'Fetch',
                '17a': 'Star vs. Echo Creek',
                '17b': 'Wand to Wand',
                '18a': 'Starstruck',
                '18b': 'Camping Trip',
                '19a': 'Starsitting',
                '19b': 'On the Job',
                '20a': 'Goblin Dogs',
                '20b': 'By the Book',
                '21a': 'Game of Flags',
                '21b': "Girls' Day Out",
                '22a': 'Sleepover',
                '22b': 'Gift of the Card',
                '23a': 'Friendenemies',
                '23b': 'Is Mystery',
                '24a': 'Hungry Larry',
                '24b': 'Spider with a Top Hat',
                '25a': 'Into the Wand',
                '25b': 'Pizza Thing',
                '26a': 'Page Turner',
                '26b': 'Naysaya',
                27: 'Bon Bon the Birthday Clown',
                '28a': 'Raid the Cave',
                '28b': 'Trickstar',
                '29a': 'Baby',
                '29b': 'Running with Scissors',
                '30a': 'Mathmagic',
                '30b': 'The Bounce Lounge',
                '31a': 'Crystal Clear',
                '31b': 'The Hard Way',
                '32a': 'Heinous',
                '32b': 'All Belts are Off',
                '33a': 'Collateral Damage',
                '33b': 'Just Friends',
                34: 'Face the Music" (Part 1)',
                35: 'Starcrushed" (Part 2)',
                '36a': 'Return to Mewni',
                '36b': 'Moon the Undaunted',
                '37a': 'Book Be Gone',
                '37b': 'Marco and the King',
                '38a': 'Puddle Defender',
                '38b': 'King Ludo',
                39: 'Toffee',
                '40a': 'Scent of a Hoodie',
                '40b': 'Rest in Pudding',
                '41a': 'Club Snubbed',
                '41b': 'Stranger Danger',
                '42a': 'Demoncism',
                '42b': 'Sophomore Slump',
                '43a': 'Lint Catcher',
                '43b': 'Trial by Squire',
                '44a': 'Princess Turdina',
                '44b': 'Starfari',
                '45a': 'Sweet Dreams',
                '45b': 'Lava Lake Beach',
                '46a': 'Death Peck',
                '46b': 'Ponymonium',
                '47a': 'Night Life',
                '47b': 'Deep Dive',
                48: 'Monster Bash',
                '49a': 'Stump Day',
                '49b': 'Holiday Spellcial',
                '50a': 'The Bogbeast of Boggabah',
                '50b': 'Total Eclipsa the Moon',
                '51a': 'Butterfly Trap',
                '51b': 'Ludo, Where Art Thou?',
                '52a': 'Is Another Mystery',
                '52b': 'Marco Jr.',
                '53a': 'Skooled!',
                '53b': 'Booth Buddies',
                '54a': 'Bam Ui Pati!',
                '54b': 'Tough Love',
                55: 'Divide" (Part 1)',
                56: 'Conquer" (Part 2)',
                57: 'Butterfly Follies" (Part 1)',
                58: 'Escape from the Pie Folk" (Part 2)',
                '59a': 'Moon Remembers',
                '59b': 'Swim Suit',
                '60a': 'Ransomgram',
                '60b': 'Lake House Fever',
                '61a': 'Yada Yada Berries',
                '61b': 'Down by the River',
                '62a': 'The Ponyhead Show!',
                '62b': 'Surviving the Spiderbites',
                '63a': 'Out of Business',
                '63b': "Kelly's World",
                64: 'Curse of the Blood Moon',
                '65a': 'Princess Quasar Caterpillar and the Magic Bell',
                '65b': 'Ghost of Butterfly Castle',
                '66a': 'Cornball!',
                '66b': "Meteora's Lesson",
                '67a': 'The Knight Shift',
                '67b': 'Queen-Napped',
                '68a': "Junkin' Janna",
                '68b': 'A Spell with No Name',
                '69a': 'A Boy and His DC-700XE',
                '69b': 'The Monster and the Queen',
                70: 'Cornonation',
                '71a': 'Doop-Doop',
                '71b': "Britta's Tacos",
                '72a': 'Beach Day',
                '72b': 'Gone Baby Gone',
                '73a': 'Sad Teen Hotline',
                '73b': 'Jannanigans',
                '74a': 'Mama Star',
                '74b': 'Ready, Aim, Fire!',
                '75a': 'The Right Way',
                '75b': 'Here to Help',
                '76a': 'Pizza Party',
                '76b': 'The Tavern at the End of the Multiverse',
                77: 'Cleaved'})

show.plot_threads = [
    ('1b', '7b', Plot.REFERENTIAL, "St. Olga's referenced"),
    ('1a', 10, Plot.CAUSAL, "Rescuing Ponyhead from St. Olga's"),
    ('12b', 13, Plot.CAUSAL, "Toffee's takeover"),
    (13, '14a', Plot.CAUSAL, "Star's new/broken wand"),
    (13, '14b', Plot.SERIAL, "Ludo stranded"),
    (13, '17b', Plot.CAUSAL, "Star's broken wand"),
    ('14b', '17b', Plot.CAUSAL, "Ludo training in magic"),
    ('19a', '19b', Plot.CAUSAL, "Buff frog's side of the babysitting day"),
    ('17b', '20b', Plot.CAUSAL, "Ludo training in magic"),
    (10, '22b', Plot.CAUSAL, "Miss Heinous' revenge"),
    ('8a', '23a', Plot.CAUSAL, "Marco/Tom relationship development"),  # Plot.CHARACTER
    ('20b', '23b', Plot.CAUSAL, "The wand's influence on Ludo"),
    #('23b', ?, Plot.CAUSAL, "Buff Frog's warning to Star"),
    (13, '25a', Plot.CAUSAL, "Toffee's finger in Star's wand"),
    (13, '26a', Plot.CAUSAL, "Magic on the fritz (later revealed to be caused by Toffee)"),
    ('8a', 27, Plot.CAUSAL, "Blood Moon curse"),
    ('22a', 27, Plot.CAUSAL, "Star's crush on Marco"),
    ('20b', 27, Plot.CAUSAL, "Ludo's plan to steal the spellbook"),
    ('25a', '36b', Plot.REFERENTIAL, "Moon and Toffee's history"),
    (27, '28a', Plot.CAUSAL, "Rescuing Glossaryck"),
    (13, '29a', Plot.CAUSAL, "Star's broken wand"),
    (27, '29a', Plot.CAUSAL, "Lost spellbook"),
    ('26a', '31a', Plot.CAUSAL, "Magic/dimensions being on the fritz"),
    (27, '31b', Plot.CAUSAL, "Glossaryck teaching Ludo"),
    ('22b', '32a', Plot.CAUSAL, "Miss Heinous' reparations"),
    (27, '33b', Plot.REFERENTIAL, "Jackie/Marco's relationship"),
    (27, '33b', Plot.CAUSAL, "Star's crush on Marco"),
    (27, 34, Plot.CAUSAL, "Star's guilt over losing the spellbook"),
    ('31b', 34, Plot.CAUSAL, "Toffee-possessed Ludo's plans"),
    ('33b', 34, Plot.CAUSAL, "Star's crush on Marco"),
    (34, 35, Plot.SERIAL, "Toffee's plans, Marco asking Star about her crush"),
    (35, '36a', Plot.SERIAL, "Marco coping with Star leaving / aftermath of battle - star/moon/high commission,"),
    ('36a', '36b', Plot.SERIAL, "Moon/Toffee's history"),
    # I'm leaning away from flashback episodes having backward causal effects since otherwise the order
    # of events causes the loop to close; I feel only actual time travel should result in backward edges)
    #('36b', '12b'/'8b', Plot.SERIAL, "Toffee's revenge"),
    (35, '37a', Plot.CAUSAL, "Aftermath of battle - Ludo"),
    ('37a', '37b', Plot.CAUSAL, "Ludo's plans to take over Mewni"),
    ('36a', '38a', Plot.CAUSAL, "Sanctuary being unusable"),
    ('37b', '38b', Plot.SERIAL, "Ludo's reign"),
    (13, 39, Plot.CAUSAL, "Toffee in the realm of magic"),
    ('36b', 39, Plot.CAUSAL, "Toffee's death fulfills Eclipsa/Moon's contract; Eclipsa freed"),
    ('38a', 39, Plot.CAUSAL, "Star attacking Ludo"),
    ('38b', 39, Plot.CAUSAL, "Ludo's reign, Marco's escape"),
    (39, '40a', Plot.CAUSAL, "Marco returning home"),
    (35, '40b', Plot.CAUSAL, "Lekmet's death"),
    ('37a', '40b', Plot.CAUSAL, "Loss of glossaryck/spellbook"),
    (34, '41a', Plot.CAUSAL, "Tom's reaction to the revelation on Song Day"),
    (39, '41b', Plot.CAUSAL, "Eclipsa freed"),
    (27, '42b', Plot.REFERENTIAL, "Jackie/Marco's relationship"),
    ('40a', '42b', Plot.CAUSAL, "Marco's return to Earth / inability to settle back in'"),
    ('40a', '43a', Plot.REFERENTIAL, "The Knight of the Wash"),
    ('42b', '43a', Plot.CAUSAL, "Marco's return to Mewni"),
    ('43a', '43b', Plot.CAUSAL, "Marco as Star's squire"),  # Referential?
    (10, '44a', Plot.CAUSAL, "Marco's facade as Princess Turdina"),
    (39, '45a', Plot.CAUSAL, "Voice calling Star (later revealed to be the unicorn she created when defeating Toffee"),
    (35, '45b', Plot.CAUSAL, "Marco's feelings about Star"),
    ('42a', '45b', Plot.CAUSAL, "Star/Tom's relationship"),  # Referential?
    ('44b', '46a', Plot.CAUSAL, "Star trying to reconcile Monsters/Mewmans"),
    ('29b', '47a', Plot.REFERENTIAL, "Marco's life in Hekapoo's dimension"),  # Causal?
    ('40b', '47a', Plot.REFERENTIAL, "Glossaryck's mental state"),
    ('45a', '47a', Plot.CAUSAL, "Star's sleep-portaling"),
    ('47a', '47b', Plot.CAUSAL, "Star's sleep-portaling and the map to her final destination"),
    ('18a', 48, Plot.REFERENTIAL, "Mina Loveberry"),
    (10, 48, Plot.CAUSAL, "Miss Heinous' revenge"),
    ('44b', 48, Plot.CAUSAL, "Star trying to reconcile Monsters/Mewmans"),
    ('49a', '49b', Plot.REFERENTIAL, "Stump Day"),
    (27, '49b', Plot.REFERENTIAL, "All-seeing eye spell"),  # Causal?
    (48, '50a', Plot.CAUSAL, "Star telling moon about Meteora"),
    ('41b', '50b', Plot.REFERENTIAL, "Moon asks Eclipsa for help investigating the records of Eclipsa's daughter"),
    ('50a', '50b', Plot.CAUSAL, "Moon investigating Star's claim about Meteora"),
    ('22a', '51a', Plot.REFERENTIAL, "The Box of Truth"),
    ('41b', '51a', Plot.CAUSAL, "Eclipsa's trial"),
    ('50b', '51a', Plot.CAUSAL, "The cover-up of Eclipsa's daughter's identity"),
    (39, '51b', Plot.CAUSAL, "Ludo finding himself"),
    ('44b', '52a', Plot.CAUSAL, "Monster/Mewmans' relationship"),
    (10, '53a', Plot.REFERENTIAL, "St. Olga's"),
    (48, '53a', Plot.CAUSAL, "Meteora investigating her past"),
    (35, '53b', Plot.CAUSAL, "Marco's feelings about Star"),
    ('51a', '54b', Plot.CAUSAL, "Meteora's past"),
    ('53a', '54b', Plot.CAUSAL, "Meteora trying to take the throne"),
    ('47b', 55, Plot.REFERENTIAL, "The realm of magic"),
    ('54b', 55, Plot.SERIAL, "Meteora's rampage, Moon missing"),
    ('40b', 56, Plot.CAUSAL, "Glossaryck's warning"),
    ('51a', 56, Plot.CAUSAL, "Star's decision about the royal line"),
    (55, 56, Plot.SERIAL, "Battle vs Meteora"),
    (56, 57, Plot.SERIAL, "Eclipsa's reign, Moon's disappearance"),
    (57, 58, Plot.SERIAL, "The search for Moon"),
    (57, '59a', Plot.CAUSAL, "Eclipsa trying to free Globgor"),
    (58, '59a', Plot.CAUSAL, "Moon resettling in the new reign"),
    (57, '59b', Plot.CAUSAL, "Eclipsa trying to free Globgor"),
    ('29b', '60a', Plot.CAUSAL, "Marco's life in Hekapoo's dimension"),
    ('53b', '60b', Plot.CAUSAL, "Star/Marco's kiss"),
    (57, '61a', Plot.CAUSAL, "Eclipsa's reign - Mewmans' distrust"),
    (57, '61b', Plot.CAUSAL, "Eclipsa's reign"),
    ('59a', '61b', Plot.CAUSAL, "Moon and River's life under Eclipsa's reign"),
    ('61a', '62a', Plot.CAUSAL, "Star trying to reconcile Eclipsa and the Mewmans"),
    ('40b', '62b', Plot.REFERENTIAL, "Remains of the spellbook"),  # Causal?
    (57, '62b', Plot.CAUSAL, "Eclipsa's prior attempts to free Globgor"),
    ('45b', '63b', Plot.CAUSAL, "Marco/Kelly's relationship"),
    ('8a', 64, Plot.CAUSAL, "Curse of the Blood Moon"),
    ('51b', '65a', Plot.CAUSAL, "Ludo's reform"),
    (48, '65b', Plot.REFERENTIAL, "Mina"),
    (57, '65b', Plot.CAUSAL, "Eclipsa's reign"),
    ('61a', '65b', Plot.CAUSAL, "The Yada Yada berries culprit"),
    ('61b', '65b', Plot.CAUSAL, "Moon/River's community"),
    ('52a', '66a', Plot.CAUSAL, "Buff Frog's departure, Monster/Mewmans' relationship"),
    (56, '66b', Plot.REFERENTIAL, "Baby Meteora"),
    ('66b', '1a', Plot.REFERENTIAL, "Glossaryck time travelling to give original Mewman settlers a magic wand"),
    ('66b', '49a', Plot.REFERENTIAL, "Glossaryck time travelling to create Stump Day"),
    ('65b', '68a', Plot.CAUSAL, "Mina's plots"),
    ('63b', '69a', Plot.CAUSAL, "Unceremonious end to Marco/Kelly's relationship (seriously wtf Daron Nefcy)"),
    ('62b', '69b', Plot.CAUSAL, "Eclipsa fixing the spellbook"),
    ('65b', 70, Plot.CAUSAL, "Mewmans' distrust of Eclipsa"),
    ('69b', 70, Plot.SERIAL, "Eclipsa/Globgor, Eclipsa's coronation"),
    ('42b', '71b', Plot.CAUSAL, "Jackie/Marco's past relationship"),
    (56, '72b', Plot.REFERENTIAL, "Baby Meteora"),
    ('71a', '72b', Plot.REFERENTIAL, "Mariposa"),
    ('71a', '73a', Plot.CAUSAL, "Tom's trip, Tom/Star's relationship"),
    ('73a', '73b', Plot.SERIAL, "Trying to reach Mewni, Marco/Star/Tom love triangle"),
    ('73b', '74a', Plot.SERIAL, "Trying to reach Mewni"),
    ('65b', '74b', Plot.CAUSAL, "Mina's plot"),
    ('74a', '74b', Plot.SERIAL, "Battle vs. Mina"),
    ('74b', '75a', Plot.SERIAL, "Battle vs. Mina"),
    ('73a', '75b', Plot.CAUSAL, "Marco/Star's relationship"),
    ('75a', '75b', Plot.SERIAL, "Battle vs. Mina - Eclipsa's dilemma"),
    ('75b', '76a', Plot.SERIAL, "Battle vs. Mina - Eclipsa's surrender"),
    ('76a', '76b', Plot.SERIAL, "Battle vs. Mina - Retreat from Mewni"),
    ('76b', 77, Plot.SERIAL, "Star destroying magic")]

show.foreshadowing = [
    ('8b', 13, Foreshadowing.MAJOR, '''Fortune cookie: "A great evil has been unleashed."; Toffee as a 'bigger bad\''''),
    ('8a', '25a', Foreshadowing.MAJOR, '''"you're not the first monster to fall victim to their magic"; Toffee/Moon's history'''),
    (10, 48, Foreshadowing.MAJOR, "Miss Heinous' cheek marks; Miss Heinous is Meteora Butterfly"),
    ('11a', 13, Foreshadowing.MAJOR, '''"Sometimes your biggest threat is right under your nose."; Toffee's coup'''),
]